#from globalpkg.global_var import work_appoint_id
from tools import tool
from globalpkg.global_var import tsi
from globalpkg.global_var import workticketid
from globalpkg.global_var import worktaskid
from globalpkg.global_var import jsaid
from globalpkg.global_var import safeclarid
from globalpkg.global_var import sql_query_work_appointid

case = '长岭项目作业许可'

#times
starttime = tool.starttime
endtime = tool.endtime
now = tool.now

#作业预约名称
name = tool.ran_name_with_str()
print("作业预约名称：",name)


#用例信息变量定义
testsuit = []
caseinfo = {}
caseinfo['id'] = 1
caseinfo['name'] = ''
caseinfo['result'] = ""
caseinfo['url'] = ''
caseinfo['data'] = ''
caseinfo['sign'] =''
caseinfo['flag'] = ''
caseinfo['isactive'] = ''
#work_appoint_id_plus1=  work_appoint_id+1
work_appoint_id_plus1 = sql_query_work_appointid+1
#作业预约创建使用ID
yuyueid = work_appoint_id_plus1
count =0
#用例信息
caseinfo['id'] = 1
caseinfo['name'] = '作业预约'
caseinfo['isactive'] = 1
#拼写预约URL
#url2='http://192.168.6.156/hse/HSE_WORK_APPOINT/cardSave?parentEntityId=&parentFuncCode=&topEntityId=%d&topFuncCode=HSE_WORK_APPOINT&dataId=%d&0.3707947936681053&contentType=json&ajax=true&tid=1'%(yuyueid,yuyueid)
#http://192.168.6.156/hse/HSE_WORK_APPOINT/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_APPOINT&0.899866420894208&contentType=json&ajax=true&tid=2000000001003
url = 'http://192.168.6.156/hse/HSE_WORK_APPOINT/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_APPOINT&0.899866420894208&contentType=json&ajax=true&tid=2000000001003'
caseinfo['url'] = url
#全票数据

data = {
	"tableName": "hse_work_appoint",
	"iscontractor": "0",
	"workunitname_no": "",
	"territorialunitid": 2000000004016,
	"worktaskid_no": 0,
	"territorialunitname": "中石化长岭分公司",
	"status": "draft",
	"dataStatus": 0,
	"ver": 1,
	"created_by": "",
	"created_dt": now,
	"updated_by": "",
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": "",
	"isspecialcondition": "",
	"plantype": "",
	"wf_audit_state": "",
	"territorialdeviceid": 2000000005066,
	"territorialdevicename": "炼油一部",
	"territorialdevicecode": "000000010300",
	"worksite": "作业地点",
	"workunit": 2000000004016,
	"workunitname": "中石化长岭分公司",
	"workname": name,
	"worktypename": "用火作业,受限空间,盲板抽堵,高处作业,起重作业,临时用电,动土作业,一般作业",
	"worktype": "dh,sx,mbcd,gc,dz,lsyd,dt,xkz",
	"appointstarttime": starttime,
	"appointendtime": endtime
}

data = {
	"tableName": "hse_work_appoint",
	"iscontractor": "0",
	"workunitname_no": "",
	"territorialunitid": 2000000004016,
	"worktaskid_no": 0,
	"territorialunitname": "中石化长岭分公司",
	"status": "draft",
	"dataStatus": 0,
	"ver": 1,
	"created_by": "",
	"created_dt": now,
	"updated_by": "",
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": "",
	"isspecialcondition": "",
	"plantype": "",
	"wf_audit_state": "",
	"territorialdeviceid": 2000000005066,
	"territorialdevicename": "炼油一部",
	"territorialdevicecode": "000000010300",
	"work_position_id": 2000000001891,
	"work_position_name": "炼油北区",
	"worksite": "作业地点",
	"workunit": 2000000004016,
	"workunitname": "中石化长岭分公司",
	"workname": name,
	"worktypename": "用火作业,受限空间,盲板抽堵,高处作业,起重作业,临时用电,动土作业,一般作业",
	"worktype": "dh,sx,mbcd,gc,dz,lsyd,dt,xkz",
	"appointstarttime": starttime,
	"appointendtime": endtime
}
caseinfo['data'] =data
testsuit.append(caseinfo.copy())
#送交用例信息

caseinfo['id'] = 2
caseinfo['name'] = '作业预约送交'
#送交接口地址
#url3='http://192.168.6.156/hse/HSE_WORK_APPOINT/wfSend?parentEntityId=&parentFuncCode=&topEntityId=%d&topFuncCode=HSE_WORK_APPOINT&dataId=%d&0.30092471197648707&contentType=json&ajax=true&tid=1'%(yuyueid,yuyueid)
#http://192.168.6.156/hse/HSE_WORK_APPOINT/wfSend?parentEntityId=&parentFuncCode=&topEntityId=2000000000431&topFuncCode=HSE_WORK_APPOINT&dataId=2000000000431&0.06389849673294723&contentType=json&ajax=true&tid=2000000001003
url = 'http://192.168.6.156/hse/HSE_WORK_APPOINT/wfSend?parentEntityId=&parentFuncCode=&topEntityId=%d&topFuncCode=HSE_WORK_APPOINT&dataId=%d&0.06389849673294723&contentType=json&ajax=true&tid=2000000001003'%(work_appoint_id_plus1,work_appoint_id_plus1)
caseinfo['url'] = url
formdata2={
	"opinion": "申请审批",
	"nodeStr": "2000000013477",
	"2000000013477": "长岭石化管理员",
	"2000000013477_id": 2000000012062
}

caseinfo['data'] =formdata2
print(caseinfo['id'] )
testsuit.append(caseinfo.copy())

#作业预约审批用例信息
caseinfo['id'] = 3
caseinfo['name'] = '作业预约审批'
#审批接口地址
#http://192.168.6.156/hse/HSE_WORK_APPOINT/wfFinish?parentEntityId=&parentFuncCode=&topEntityId=2000000000430&topFuncCode=HSE_WORK_APPOINT&dataId=2000000000430&0.7556673624348265&contentType=json&ajax=true&tid=2000000001003
url4='http://192.168.6.156/hse/HSE_WORK_APPOINT/wfFinish?parentEntityId=&parentFuncCode=&topEntityId=%d&topFuncCode=HSE_WORK_APPOINT&dataId=%d&0.7556673624348265&contentType=json&ajax=true&tid=2000000001003'%(work_appoint_id_plus1,work_appoint_id_plus1)
caseinfo['url'] = url4
#参数
data = {
	"opinion": "同意",
	"cC": "2000000012062",
	"cCName": "长岭石化管理员",
	"nickName": "cl",
	"is_normal_finish": "true",
	"nodeStr": ""
}
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#安全分析及交底保存
casename = '安全分析及交底保存'
caseinfo['id'] = 4
caseinfo['name'] = casename
#http://192.168.6.156/hse/HSE_SAFETY_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_SAFETY_TASK&0.666941462228346&contentType=json&ajax=true&tid=2000000001003
urlfenxi ='http://192.168.6.156/hse/HSE_SAFETY_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_SAFETY_TASK&0.666941462228346&contentType=json&ajax=true&tid=2000000001003'
formdatafenxi = {
	"tableName": "hse_safety_task",
	"wf_create_user": 2000000012062,
	"iscontractor": "0",
	"workstatus": "draft",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000012062,
	"created_dt":now,
	"updated_by": 2000000012062,
	"updated_dt":now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": "",
	"analyze_type": "jsa",
	"projecttype": "rcjx",
	"workname": name,
	"territorialunitid": 2000000005066,
	"territorialunitname": "炼油一部",
	"territorialdeviceid": 2000000005066,
	"territorialdevicename": "炼油一部",
	"territorialdevicecode": "000000010300",
	"work_position_id": 2000000001891,
	"work_position_name": "炼油北区",
	"site": "作业地点",
	"planstarttime": starttime,
	"planendtime": endtime,
	"workcontent": "作业内容",
	"worktickettype_name": "用火作业,受限空间,盲板抽堵,高处作业,起重作业,临时用电,动土作业,一般作业",
	"worktickettype": "dh,sx,mbcd,gc,dz,lsyd,dt,xkz"
}
data = {
	"tableName": "hse_safety_task",
	"wf_create_user": 2000000012062,
	"iscontractor": "0",
	"workstatus": "draft",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000012062,
	"created_dt": now,
	"updated_by": 2000000012062,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": "",
	"analyze_type": "jsa",
	"projecttype": "rcjx",
	"territorialunitid": 2000000004016,
	"territorialunitname": "中石化长岭分公司",
	"workname": name,
	"territorialdeviceid": 2000000005066,
	"territorialdevicename": "炼油一部",
	"territorialdevicecode": "000000010300",
	"work_position_id": 2000000001891,
	"work_position_name": "炼油北区",
	"site": "作业地点",
	"planstarttime": starttime,
	"planendtime": endtime,
	"workcontent": "作业内容",
	"worktickettype_name": "用火作业,受限空间,盲板抽堵,高处作业,起重作业,临时用电,动土作业,一般作业",
	"worktickettype": "dh,sx,mbcd,gc,dz,lsyd,dt,xkz"
}
caseinfo['url'] = urlfenxi
caseinfo['data'] = data
testsuit.append(caseinfo.copy())



#jsaidxx = work_appoint_id-33
jsaidx = jsaid+1
print ("安全分析列表使用ID:",jsaidx)


#安全分析步骤添加接口用例信息
casename = '安全分析步骤添加'
count =count+1
caseid = count
caseinfo['id'] = 5
caseinfo['name'] = casename
topEntityId = jsaidx +40
#http://192.168.6.156/hse/HSE_SAFETY_ANALYSIS_STEP/cardSave?parentEntityId=2000000000830&parentFuncCode=HSE_SAFETY_ANALYSIS&topEntityId=2000000000870&topFuncCode=HSE_SAFETY_TASK&0.7124130928687566&contentType=json&ajax=true&tid=2000000001003
url ='http://192.168.6.156/hse/HSE_SAFETY_ANALYSIS_STEP/cardSave?parentEntityId=%d&parentFuncCode=HSE_SAFETY_ANALYSIS&topEntityId=%d&topFuncCode=HSE_SAFETY_TASK&0.7124130928687566&contentType=json&ajax=true&tid=2000000001003'%(jsaidx,topEntityId)
#url = 'http://192.168.6.156/hse/HSE_SAFETY_ANALYSIS_STEP/cardSave?parentEntityId=2000000000830&parentFuncCode=HSE_SAFETY_ANALYSIS&topEntityId=2000000000870&topFuncCode=HSE_SAFETY_TASK&0.7124130928687566&contentType=json&ajax=true&tid=2000000001003'

data = {
	"tableName": "hse_safety_analysis_step",
	"qualify_level": "no_qualify",
	"jsaid": jsaidx,
	"dataStatus": 0,
	"ver": 1,
	"created_by": "",
	"created_dt": "2020-06-17 11:39:49",
	"updated_by": "",
	"updated_dt": "2020-06-17 11:39:49",
	"df": 0,
	"tenantid": 2000000001003,
	"ts": "",
	"evaluate_type": "",
	"worktickettype_name": "一般作业",
	"worktickettype": "xkz",
	"worknumber": "10086",
	"step_name": "步骤活动"
}
caseinfo['url'] = url
caseinfo['data'] =data
#testsuit.append(caseinfo.copy())

#安全分析步保存加接口用例信息

casename = '安全分析保存'
count =count+1
caseid = count
caseinfo['id'] = 6
caseinfo['name'] = casename
print("topEntityId",topEntityId)
print("jsaidx",jsaidx)
#http://192.168.6.156/hse/HSE_SAFETY_ANALYSIS/cardSave?parentEntityId=2000000000876&parentFuncCode=HSE_SAFETY_TASK&topEntityId=2000000000876&topFuncCode=HSE_SAFETY_TASK&dataId=2000000000836&0.6015172226353962&contentType=json&ajax=true&tid=2000000001003
url=  'http://192.168.6.156/hse/HSE_SAFETY_ANALYSIS/cardSave?parentEntityId=%d&parentFuncCode=HSE_SAFETY_TASK&topEntityId=%d&topFuncCode=HSE_SAFETY_TASK&dataId=%d&0.6015172226353962&contentType=json&ajax=true&tid=2000000001003'%(topEntityId,topEntityId,jsaidx)
#url = 'http://192.168.6.156/hse/HSE_SAFETY_ANALYSIS/cardSave?parentEntityId=2000000000876&parentFuncCode=HSE_SAFETY_TASK&topEntityId=2000000000876&topFuncCode=HSE_SAFETY_TASK&dataId=2000000000836&0.6015172226353962&contentType=json&ajax=true&tid=2000000001003'

data = {
	"tableName": "hse_safety_analysis",

	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000012062,
	"created_dt": now,
	"updated_by": 2000000012062,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": "",
	"jsaid": jsaidx,
	"jsa_templete_name": "炼油一部安全分析数据模板",
	"jsa_templete_id": 2000000000140,
	"temp_type": "",
	"jsa_monitor_userid": "",
	"jsa_monitor_name": "测试用户",
	"jsa_menber_userids": "",
	"jsa_menber_username": "测试用户",
	"analyze_time": now,
	"worktickettype": "",
	"equip_stuff": "",
	"worktaskid": topEntityId,
	"workstatus": "",
	"worktype": "jsa",
	"revampandadvide": "",
	"inspection_name": "",
	"work_position_id": 2000000001891,
	"projecttype": "",
	"workname": "",
	"workunitname": "",
	"reference": "",
	"iscontractor": "",
	"territorialunitid": "",
	"territorialunitname": "",
	"planendtime": "",
	"reviewer": "",
	"site": "",
	"worknumber": "",
	"workunit": "",
	"craftprocess": "",
	"planstarttime": "",
	"workcontent": "",
	"isnew": "",
	"wf_instance": "",
	"wf_current_user": "",
	"wf_audit_time": "",
	"wf_current_nodeid": "",
	"wf_type": "",
	"wf_create_user": "",

	"sourcejsaid": "",
	"remainsrisk_level": "",
	"risk_level": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())
'''
#安全交底，环境影响大
casename = '安全交底'
count =count+1
caseid = count
caseinfo['id'] = 7
caseinfo['name'] = casename
#worktaskidxx = jsaidxx+17
anquansongjiaoid = safeclarid+1
safeclaridxx = safeclarid+1
print ("送交ID:",safeclaridxx)
url='http://192.168.6.156/hse/HSE_SAFETY_DISCLOSURE/cardSave?parentEntityId=%d&parentFuncCode=HSE_SAFETY_TASK_RISK&topEntityId=%d&topFuncCode=HSE_SAFETY_TASK_RISK&dataId=%d&0.7447101068947941&contentType=json&ajax=true&tid=1'%(jsaidxx,jsaidxx,safeclaridxx)

data = {
	"tableName": "hse_safety_disclosure",
	"additional_content": "",
	"confirm_content": "1、已清楚作业区域及周边生产作业情况\r\n2、已清楚本次作业的安全风险（JSA）\r\n3、已清楚本次作业的具体安全要求（作业许可证中的控制措施）\r\n4、已对本次作业现场安全措施进行了检查确认\r\n5、已清楚本次作业涉及的作业许可证的有限期限 \r\n6、已掌握个人防护用具正确佩戴使用方法\r\n7、已清楚突发情况下的应急避险方法",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": "",
	"safeclarid": safeclaridxx,
	"projecttype": "",
	"safe_name": "长庆石化安全交底",
	"worktype": "aqjd",
	"workstatus": "draft",
	"scopeandenv": "",
	"workrisk": "",
	"preventmeasure": "",
	"emermeasure": "",
	"othermatter": "",
	"safe_content": "长庆石化安全交底",
	"safe_clar_temp_id": 2000000001040,
	"safe_clar_temp_name": "",
	"worktaskid": jsaid,
	"work_position_id": 2000000002019
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())
'''

#安全送交接口用例信息

casename = '安全送交'
count =count+1
caseid = count
caseinfo['id'] = 8
caseinfo['name'] = casename
#http://192.168.6.156/hse/HSE_SAFETY_TASK/wfSend?parentEntityId=&parentFuncCode=&topEntityId=2000000000886&topFuncCode=HSE_SAFETY_TASK&dataId=2000000000886&0.6665362277729903&contentType=json&ajax=true&tid=2000000001003
url = 'http://192.168.6.156/hse/HSE_SAFETY_TASK/wfSend?parentEntityId=&parentFuncCode=&topEntityId=%d&topFuncCode=HSE_SAFETY_TASK&dataId=%d&0.6665362277729903&contentType=json&ajax=true&tid=2000000001003'%(topEntityId,topEntityId)
data = {}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())


#作业任务添加接口用例信息

casename = '作业任务添加'

caseinfo['id'] = 9
caseinfo['name'] = casename
#http://192.168.6.156/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.11384446004454407&contentType=json&ajax=true&tid=2000000001003
url = 'http://192.168.6.156/hse/HSE_WORK_TASK/cardSave?parentEntityId=&parentFuncCode=&topFuncCode=HSE_WORK_TASK&0.11384446004454407&contentType=json&ajax=true&tid=2000000001003'

jsaidx= jsaid+1


data = {
	"tableName": "hse_work_task",
	"iscontractor": "0",
	"work_appoint_name": "Created_by_Python_mtO1UH",
	"applyunitname": "中石化长岭分公司",
	"territorialunitid": 2000000004016,
	"work_property": "plan",
	"territorialunitname": "中石化长岭分公司",
	"territorialunitcode": "00000001",
	"applyunitid": 2000000004016,
	"jsa_code": "中石化_AQFX20200617018",
	"workstatus": "draft",
	"autorisklevel": 0,
	"dataStatus": 0,
	"ver": 1,
	"created_by": "",
	"created_dt": now,
	"updated_by": "",
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": "",
	"projecttype": "rcjx",
	"isspecialcondition": "",
	"eq_position": "",
	"workname": name,
	"jsaid": jsaidx,
	"site": "作业地点",
	"workunit": 2000000004016,
	"workunitname": "中石化长岭分公司",
	"work_position_id": 2000000001891,
	"work_position_name": "炼油北区",
	"worktickettype": "dh,sx,mbcd,gc,dz,lsyd,dt,xkz",
	"worktickettype_name": "用火作业,受限空间,盲板抽堵,高处作业,起重作业,临时用电,动土作业,一般作业",
	"territorialdevicename": "炼油一部",
	"workcontent": "作业内容",
	"planstarttime": starttime,
	"planendtime": endtime,
	"work_appoint_id": 2000000000450,
	"equipmentname": "",
	"equipmentnumber": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())



worktaskidx = worktaskid+1
#worktaskidxx = worktaskid-37
print("作业任务列表ID-worktaskid:",worktaskidx)
#作业任务提交接口用例信息

casename = '作业任务提交'

caseinfo['id'] = 10
caseinfo['name'] = casename
#http://192.168.6.156/hse/HSE_WORK_TASK/hse_work_task_submit?parentEntityId=&parentFuncCode=&topEntityId=2000000002850&topFuncCode=HSE_WORK_TASK&dataId=2000000002850&0.8393620359994138&contentType=json&ajax=true&tid=2000000001003
url = 'http://192.168.6.156/hse/HSE_WORK_TASK/hse_work_task_submit?parentEntityId=&parentFuncCode=&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&0.8393620359994138&contentType=json&ajax=true&tid=2000000001003'%(worktaskidx,worktaskidx)
data = {
	"tableName": "hse_work_task",
	"task_worktype_code": "",
	"hasrescueplan": "",
	"territorialdeviceid": "",
	"drawshow": "",
	"cywlqfyxzz": "",
	"autorisklevel": 0,
	"worktools": "",
	"othercontent": "",
	"equipmentcode": "",
	"ishasworker": "",
	"territorialdevicename": "炼油一部",
	"hasdrawpaper": "",
	"hassafetyplan": "",
	"worker": "",
	"card_code": "",
	"reminder": "",
	"constructionscheme": "",
	"reminderid": "",
	"worktickettype_name": "用火作业,受限空间,盲板抽堵,高处作业,起重作业,临时用电,动土作业,一般作业",
	"task_worktype_name": "",
	"standardmaintenance": "",
	"attaches": "",
	"material_medium": "",
	"risksmeasures": "",
	"territorialdevicecode": "",
	"isrecord": "",
	"persistent_type": "",
	"flights": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000012062,
	"created_dt": now,
	"updated_by": 2000000012062,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": "",
	"worktaskid": worktaskidx,
	"workname": name,
	"work_position_name": "炼油北区",
	"work_appoint_name": "Created_by_Python_mtO1UH",
	"actualstarttime": "",
	"actualendtime": "",
	"isgas_detection": "",
	"delayreason": "",
	"cancelreason": "",
	"pause": 0,
	"isupgrade": "",
	"sourcetaskid": "",
	"nlglnumber": "",
	"isreport": "",
	"iswfnotreport": 0,
	"gas_standard_type": "",
	"parentid": "",
	"lsydticketid": "",
	"dqyzticketid": "",
	"dqezticketid": "",
	"task_pause": "",
	"territorialunitid": 2000000004016,
	"territorialunitname": "中石化长岭分公司",
	"site": "作业地点",
	"work_property": "plan",
	"equipmentnumber": "",
	"workunit": 2000000004016,
	"workunitname": "中石化长岭分公司",
	"projecttype": "rcjx",
	"iscontractor": "0",
	"planstarttime": starttime,
	"planendtime": endtime,
	"worktickettype": "dh,sx,mbcd,gc,dz,lsyd,dt,xkz",
	"workstatus": "draft",
	"applyunitid": 2000000004016,
	"applyunitname": "中石化长岭分公司",
	"created_by_name": "长岭石化管理员",
	"updated_by_name": "长岭石化管理员",
	"workcontent": "作业内容",
	"woid": "",
	"wo_code": "",
	"territorialunitcode": "00000001",
	"equt_position": "",
	"position_name": "",
	"equipmentname": "",
	"safeclar": "",
	"safecode": "",
	"work_position_id": 2000000001891,
	"jsa_code": "中石化_AQFX20200617018",
	"jsaid": 2000000000887,
	"work_appoint_id": 2000000000450,
	"wf_current_nodeid": "",
	"wf_audit_time": "",
	"task_risklevel": "",
	"task_closereason": "",
	"task_closetype": "",
	"wf_current_user": "",
	"wf_audit_state": "0",
	"wf_create_user": 2000000012062,
	"wf_instance": "",
	"wf_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"jobstatus": "",
	"weekplanid": "",
	"plan_type": 3,
	"gasdetecttype": "",
	"close_type": "",
	"closereason": "",
	"jsa_code2": "",
	"jsaid2": "",
	"isproprietor": "",
	"planendtime_org": "",
	"specialenvironment": "",
	"gas_aging": "",
	"safetyanalysisid": "",
	"safetyanalysiscode": "",
	"isspecialcondition": "",
	"specialcondition": "",
	"task_risklevel_org": "",
	"eq_position": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())




caseinfo['id'] = 11
caseinfo['name'] = '作业许可证保存'
#作业许可证 库hse_work_ticket
workticketidx = workticketid+7
#work_appoint_idx = work_appoint_id +1
ts = tsi+7
print(caseinfo['name'],workticketidx)
#http://192.168.6.156/hse/HSE_WORK_TICKET_XKZ_GB/cardSave?parentEntityId=2000000002853&parentFuncCode=HSE_WORK_TASK&topEntityId=2000000002853&topFuncCode=HSE_WORK_TASK&dataId=2000000003380&ts=1592375027435&0.6988032340417722&contentType=json&ajax=true&tid=2000000001003
url = 'http://192.168.6.156/hse/HSE_WORK_TICKET_XKZ_GB/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=%d&0.6988032340417722&contentType=json&ajax=true&tid=2000000001003'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "",
	"radiosourcenum": "",
	"workside": "",
	"relevantdoc": "",
	"safedistance": "",
	"hazard_factors": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "00000001",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000012062,
	"created_dt": now,
	"updated_by": 2000000012062,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": 0,
	"operator": "",
	"worktimeconsum": "",
	"task_pause": "",
	"projecttype": "rcjx",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "xkz",
	"territorialunitid": 2000000004016,
	"territorialunitname": "中石化长岭分公司",
	"applyunitid": 2000000004016,
	"applyunitname": "中石化长岭分公司",
	"worknumber": "",
	"worklevel": "",
	"site": "作业地点",
	"workway": "per,work",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容",
	"workunit": 2000000004016,
	"workunitname": "中石化长岭分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "长岭石化管理员",
	"updated_by_name": "长岭石化管理员",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": "2",
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000001891,
	"isgas_detection": "1",
	"gas_aging": "4",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "一般作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"is_fire_exit": "",
	"work_position_name": "炼油北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"istask": "1"
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

caseinfo['id'] = 12
caseinfo['name'] = '作业许可证-措施添加'
#作业许可证 库hse_work_ticket
workticketidx = workticketid+7
#work_appoint_idx = work_appoint_id +1
ts = tsi+7
print(caseinfo['name'],workticketidx)
#http://192.168.6.156/hse/HSE_WORK_TASK_MEASURE/cardSave?parentEntityId=2000000003388&parentFuncCode=HSE_WORK_TICKET_XKZ_GB&topEntityId=2000000002854&topFuncCode=HSE_WORK_TASK&0.6867825974170922&contentType=json&ajax=true&tid=2000000001003
url = 'http://192.168.6.156/hse/HSE_WORK_TASK_MEASURE/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TICKET_XKZ_GB&topEntityId=%d&topFuncCode=HSE_WORK_TASK&0.6867825974170922&contentType=json&ajax=true&tid=2000000001003'%(workticketidx,worktaskidx)
data = {
	"tableName": "hse_work_task_measure",
	"attachphoto": "0",
	"auditpersonname": "0",
	"worktype": "xkz",
	"ismustphoto": "0",
	"workticketid": workticketidx,
	"ismustconfirm": "0",
	"dataStatus": 0,
	"ver": 1,
	"created_by": "",
	"created_dt": now,
	"updated_by": "",
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": "",
	"isconfirm": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())


#作业许可证提交
caseinfo['id'] = 13
caseinfo['name'] = '作业许可证提交'
#http://192.168.6.156/hse/HSE_WORK_TICKET_XKZ_GB/hse_work_ticket_submit?parentEntityId=2000000002854&parentFuncCode=HSE_WORK_TASK&topEntityId=2000000002854&topFuncCode=HSE_WORK_TASK&dataId=2000000003388&ts=1592375681490&0.8747140621906206&contentType=json&ajax=true&tid=2000000001003
url = 'http://192.168.6.156/hse/HSE_WORK_TICKET_XKZ_GB/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=%d&0.8747140621906206&contentType=json&ajax=true&tid=2000000001003'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "",
	"radiosourcenum": "",
	"workside": "",
	"relevantdoc": "",
	"safedistance": "",
	"hazard_factors": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "00000001",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000012062,
	"created_dt": now,
	"updated_by": 2000000012062,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": 0,
	"operator": "",
	"worktimeconsum": "",
	"task_pause": "",
	"projecttype": "rcjx",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "xkz",
	"territorialunitid": 2000000004016,
	"territorialunitname": "中石化长岭分公司",
	"applyunitid": 2000000004016,
	"applyunitname": "中石化长岭分公司",
	"worknumber": "",
	"worklevel": "",
	"site": "作业地点",
	"workway": "per,work",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容",
	"workunit": 2000000004016,
	"workunitname": "中石化长岭分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "长岭石化管理员",
	"updated_by_name": "长岭石化管理员",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 2,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000001891,
	"isgas_detection": "1",
	"gas_aging": 4,
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "一般作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"is_fire_exit": "",
	"work_position_name": "炼油北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"istask": "1"
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())


caseinfo['id'] = 14
caseinfo['name'] = '动火作业保存'
#动火作业保存全票时 
workticketidx = workticketid+3
#work_appoint_idx = work_appoint_id +1
ts = tsi+3
print(caseinfo['name'],workticketidx)
#http://192.168.6.156/hse/HSE_WORK_TICKET_DH/cardSave?parentEntityId=2000000002855&parentFuncCode=HSE_WORK_TASK&topEntityId=2000000002855&topFuncCode=HSE_WORK_TASK&dataId=2000000003392&ts=1592376641301&0.031214357794258296&contentType=json&ajax=true&tid=2000000001003
url = 'http://192.168.6.156/hse/HSE_WORK_TICKET_DH/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=%d&0.031214357794258296&contentType=json&ajax=true&tid=2000000001003'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "",
	"radiosourcenum": "",
	"workside": "",
	"relevantdoc": "",
	"safedistance": "",
	"hazard_factors": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "00000001",
	"ticketdealphoto": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000012062,
	"created_dt": now,
	"updated_by": 2000000012062,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"task_pause": "",
	"projecttype": "rcjx",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "dh",
	"territorialunitid": 2000000004016,
	"territorialunitname": "中石化长岭分公司",
	"applyunitid": 2000000004016,
	"applyunitname": "中石化长岭分公司",
	"worknumber": "",
	"worklevel": "gb_dh_workLevel01",
	"site": "作业地点",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容",
	"workunit": 2000000004016,
	"workunitname": "中石化长岭分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "长岭石化管理员",
	"updated_by_name": "长岭石化管理员",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000001891,
	"isgas_detection": "1",
	"gas_aging": "4",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "用火作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"is_fire_exit": "",
	"work_position_name": "炼油北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#动火作业提交
caseinfo['id'] = 14
caseinfo['name'] = '动火作业提交'
#http://192.168.6.156/hse/HSE_WORK_TICKET_DH/hse_work_ticket_submit?parentEntityId=2000000002859&parentFuncCode=HSE_WORK_TASK&topEntityId=2000000002859&topFuncCode=HSE_WORK_TASK&dataId=2000000003424&ts=1592377816140&0.18132470759745045&contentType=json&ajax=true&tid=2000000001003
url = 'http://192.168.6.156/hse/HSE_WORK_TICKET_DH/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK&topEntityId=%d&topFuncCode=HSE_WORK_TASK&dataId=%d&ts=%d&0.18132470759745045&contentType=json&ajax=true&tid=2000000001003'%(worktaskidx,worktaskidx,workticketidx,ts)

data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "",
	"radiosourcenum": "",
	"workside": "",
	"relevantdoc": "",
	"safedistance": "",
	"hazard_factors": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "00000001",
	"ticketdealphoto": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 2000000012062,
	"created_dt": now,
	"updated_by": 2000000012062,
	"updated_dt": now,
	"df": 0,
	"tenantid": 2000000001003,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": 0,
	"isfireday": 0,
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"task_pause": "",
	"projecttype": "rcjx",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "dh",
	"territorialunitid": 2000000004016,
	"territorialunitname": "中石化长岭分公司",
	"applyunitid": 2000000004016,
	"applyunitname": "中石化长岭分公司",
	"worknumber": "",
	"worklevel": "gb_dh_workLevel01",
	"site": "作业地点",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容",
	"workunit": 2000000004016,
	"workunitname": "中石化长岭分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "长岭石化管理员",
	"updated_by_name": "长岭石化管理员",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000001891,
	"isgas_detection": "1",
	"gas_aging": 4,
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": "0",
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "用火作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"is_fire_exit": "",
	"work_position_name": "炼油北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

'''
#
caseinfo['id'] = 15
caseinfo['name'] = '受限作业保存'

workticketidx = workticketid+5
ts = tsi+5
print(caseinfo['name'],workticketidx)
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_SX_MCQ/cardSave?parentEntityId=2000000004515&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004515&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006204&ts=1591779828324&0.8214154673307006&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_SX_MCQ/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.8214154673307006&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comone01,comone02,comone03,comone05,comone06,comone07",
	"radiosourcenum": "",
	"relevantdoc": "",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "sx",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "mcq_sx_workLevel01",
	"site": "作业地点123",
	"workway": "mcq_sxfs11,mcq_sxfs12,mcq_sxfs13,mcq_sxfs14,mcq_sxfs15,mcq_sxfs16,mcq_sxfs09,mcq_sxfs10,mcq_sxfs08,mcq_sxfs07,mcq_sxfs06,mcq_sxfs05,mcq_sxfs04,mcq_sxfs03,mcq_sxfs02,mcq_sxfs01",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": "1",
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "1",
	"hashseplan": "",
	"hasemergencyplan": "1",
	"hasdrawpaper": "1",
	"haschecklist": "",
	"hasrescueplan": "1",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": "1",
	"gas_aging": 4,
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "受限空间",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#受限作业提交
caseinfo['id'] = 16
caseinfo['name'] = '受限作业提交'
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_SX_MCQ/hse_work_ticket_submit?parentEntityId=2000000004517&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004517&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006224&ts=1591781327182&0.49287209088923034&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_SX_MCQ/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.49287209088923034&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)

data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comone01,comone02,comone03,comone05,comone06,comone07",
	"radiosourcenum": "",
	"relevantdoc": "",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "sx",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "mcq_sx_workLevel01",
	"site": "作业地点123",
	"workway": "mcq_sxfs11,mcq_sxfs12,mcq_sxfs13,mcq_sxfs14,mcq_sxfs15,mcq_sxfs16,mcq_sxfs09,mcq_sxfs10,mcq_sxfs08,mcq_sxfs07,mcq_sxfs06,mcq_sxfs05,mcq_sxfs04,mcq_sxfs03,mcq_sxfs02,mcq_sxfs01",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 1,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "1",
	"hashseplan": "",
	"hasemergencyplan": "1",
	"hasdrawpaper": "1",
	"haschecklist": "",
	"hasrescueplan": "1",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": "1",
	"gas_aging": 4,
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "受限空间",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

caseinfo['id'] = 17
caseinfo['name'] = '吊装作业保存'
#
workticketidx = workticketid+6

ts = tsi+6
print(caseinfo['name'],workticketidx)
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DZ_MCQ/cardSave?parentEntityId=2000000004518&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004518&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006235&ts=1591781865298&0.7881595889416673&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DZ_MCQ/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.7881595889416673&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comone01,comone02,comone03,comone04,comone05,comone06",
	"radiosourcenum": "",
	"relevantdoc": "",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "dz",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "mcq_dz_workLevel01",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname":name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "1",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "5",
	"loaddegree": "",
	"loadrate": "20",
	"objectnorm": "4*4*4",
	"loadmass": "1",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "大木头",
	"loadhigh": "19",
	"worktask_name": name,
	"worktype_name": "吊装作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#受限作业提交
caseinfo['id'] = 18
caseinfo['name'] = '吊装作业提交'
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DZ_MCQ/hse_work_ticket_submit?parentEntityId=2000000004519&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004519&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006245&ts=1591835920695&0.2895095529533147&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DZ_MCQ/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.2895095529533147&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)

data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comone01,comone02,comone03,comone04,comone05,comone06",
	"radiosourcenum": "",
	"relevantdoc": "",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "dz",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "mcq_dz_workLevel01",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "1",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "5",
	"loaddegree": "",
	"loadrate": "20",
	"objectnorm": "4*4*4",
	"loadmass": "1",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "大木头",
	"loadhigh": "19",
	"worktask_name": name,
	"worktype_name": "吊装作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#临时用电保存
caseinfo['id'] = 19
caseinfo['name'] = '临时用电保存'
workticketidx = workticketid+1
ts = tsi+1
print(caseinfo['name'],workticketidx)
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_LSYD_MCQ/cardSave?parentEntityId=2000000004520&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004520&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006250&ts=1591836199628&0.22774814767641516&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_LSYD_MCQ/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.22774814767641516&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "lsyd",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "202006lsyd043",
	"worklevel": "",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "电源接入点",
	"workvoltage": "工作电压",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "临时用电",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#受限作业提交
caseinfo['id'] = 20
caseinfo['name'] = '临时用电提交'
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_LSYD_MCQ/hse_work_ticket_submit?parentEntityId=2000000004521&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004521&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006260&ts=1591836539464&0.894764926006997&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_LSYD_MCQ/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.894764926006997&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)

data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "",
	"radiosourcenum": "",
	"relevantdoc": "",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "lsyd",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "202006lsyd043",
	"worklevel": "",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "电源接入点",
	"workvoltage": "工作电压",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "临时用电",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#高处作业保存
caseinfo['id'] = 21
caseinfo['name'] = '高处作业保存'
workticketidx = workticketid+9
ts = tsi+9
print(caseinfo['name'],workticketidx)
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_GC_MCQ/cardSave?parentEntityId=2000000004522&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004522&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006278&ts=1591837035769&0.23750256010188697&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_GC_MCQ/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.23750256010188697&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comtwo01,comtwo02,comtwo04,comtwo03,comtwo05,comtwo06",
	"radiosourcenum": "",
	"relevantdoc": "",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "gc",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "mcq_gc_workLevel01",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "1",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "1",
	"haschecklist": "",
	"hasrescueplan": "1",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "高处作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#高处作业提交
caseinfo['id'] = 22
caseinfo['name'] = '高处作业提交'
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_GC_MCQ/hse_work_ticket_submit?parentEntityId=2000000004523&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004523&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006288&ts=1591838465684&0.8602956738456475&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_GC_MCQ/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.8602956738456475&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)

data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comtwo01,comtwo02,comtwo04,comtwo03,comtwo05,comtwo06",
	"radiosourcenum": "",
	"relevantdoc": "",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "gc",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "mcq_gc_workLevel01",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "1",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "1",
	"haschecklist": "",
	"hasrescueplan": "1",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "高处作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#管线作业保存
caseinfo['id'] = 23
caseinfo['name'] = '管线作业保存'
workticketidx = workticketid+3
ts = tsi+3
print(caseinfo['name'],workticketidx)
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_GX_MCQ/cardSave?parentEntityId=2000000004527&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004527&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006300&ts=1591839629701&0.08776440017753662&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_GX_MCQ/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.08776440017753662&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comone01,comone02,comone03,comone04,comone05,comone06",
	"radiosourcenum": "",
	"relevantdoc": "rd01,rd02,rd03,rd04",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "gx",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "1",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "1",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 1,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "管线/设备打开",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": "",
	"risk_rank": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#管线作业提交
caseinfo['id'] = 24
caseinfo['name'] = '管线作业提交'
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_GX_MCQ/hse_work_ticket_submit?parentEntityId=2000000004527&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004527&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006300&ts=1591839762877&0.2940449411368411&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_GX_MCQ/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.2940449411368411&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)

data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comone01,comone02,comone03,comone04,comone05,comone06",
	"radiosourcenum": "",
	"relevantdoc": "rd01,rd02,rd03,rd04",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"risk_rank": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "gx",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "1",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "1",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "管线/设备打开",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#挖掘作业保存
caseinfo['id'] = 25
caseinfo['name'] = '挖掘作业保存'
workticketidx = workticketid+2
ts = tsi+2
print(caseinfo['name'],workticketidx)
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DT_MCQ/cardSave?parentEntityId=2000000004528&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004528&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006309&ts=1591840183410&0.7322566354763398&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DT_MCQ/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.7322566354763398&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comone01,comone02,comone03,comone04,comone05,comone06",
	"radiosourcenum": "",
	"relevantdoc": "rd01,rd02,rd03,rd04,rd05",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "eqp01,eqp02",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "dt",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "挖掘作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#挖掘作业提交
caseinfo['id'] = 26
caseinfo['name'] = '挖掘作业提交'
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DT_MCQ/hse_work_ticket_submit?parentEntityId=2000000004528&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004528&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000006309&ts=1591840368574&0.1537674191009537&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DT_MCQ/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.1537674191009537&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)

data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comone01,comone02,comone03,comone04,comone05,comone06",
	"radiosourcenum": "",
	"relevantdoc": "rd01,rd02,rd03,rd04,rd05",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "eqp01,eqp02",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "dt",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "测试用户",
	"updated_by_name": "测试用户",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "挖掘作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#断路作业保存
caseinfo['id'] = 27
caseinfo['name'] = '断路作业保存'
workticketidx = workticketid+8
ts = tsi+8
print(caseinfo['name'],workticketidx)
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DL_MCQ/cardSave?parentEntityId=2000000004251&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004251&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000005717&ts=1591841335187&0.09230460814488173&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DL_MCQ/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.09230460814488173&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "",
	"radiosourcenum": "",
	"relevantdoc": "rd01,rd02,rd03,rd04,rd05",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "dl",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "断路原因",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "卢健",
	"updated_by_name": "卢健",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "断路作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#断路作业提交
caseinfo['id'] = 28
caseinfo['name'] = '断路作业提交'
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DL_MCQ/hse_work_ticket_submit?parentEntityId=2000000004251&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004251&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000005717&ts=1591841498887&0.6530686162830868&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_DL_MCQ/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.6530686162830868&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)

data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "",
	"radiosourcenum": "",
	"relevantdoc": "rd01,rd02,rd03,rd04,rd05",
	"safedistance": "",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "dl",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "断路原因",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "卢健",
	"updated_by_name": "卢健",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "",
	"sourcecode": "",
	"sourcestrength": "",
	"suprange": "",
	"controlrange": "",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "断路作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#射线作业保存
caseinfo['id'] = 29
caseinfo['name'] = '射线作业保存'
workticketidx = workticketid+10
ts = tsi+10
print(caseinfo['name'],workticketidx)
#http://http://192.168.6.27:6030/hse/HSE_WORK_TICKET_SHEX_MCQ/cardSave?parentEntityId=2000000004252&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004252&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000005729&ts=1591842038600&0.8902545084000464&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_SHEX_MCQ/cardSave?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.8902545084000464&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)
data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comtwo01,comtwo02,comtwo03,comtwo04,comtwo05,comtwo06",
	"radiosourcenum": "1",
	"relevantdoc": "rd01,rd02,rd04,rd03,rd05",
	"safedistance": "10",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "shex",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "卢健",
	"updated_by_name": "卢健",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "1",
	"sourcecode": "22",
	"sourcestrength": "2",
	"suprange": "12",
	"controlrange": "2",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "射线作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())

#射线作业提交
caseinfo['id'] = 30
caseinfo['name'] = '射线作业提交'
#http://192.168.6.27:6030/hse/HSE_WORK_TICKET_SHEX_MCQ/hse_work_ticket_submit?parentEntityId=2000000004255&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=2000000004255&topFuncCode=HSE_WORK_TASK_MCQ&dataId=2000000005759&ts=1591843746360&0.046230678614398&contentType=json&ajax=true&tid=1
url = 'http://192.168.6.27:6030/hse/HSE_WORK_TICKET_SHEX_MCQ/hse_work_ticket_submit?parentEntityId=%d&parentFuncCode=HSE_WORK_TASK_MCQ&topEntityId=%d&topFuncCode=HSE_WORK_TASK_MCQ&dataId=%d&ts=%d&0.046230678614398&contentType=json&ajax=true&tid=1'%(worktaskidx,worktaskidx,workticketidx,ts)

data = {
	"tableName": "hse_work_ticket",
	"clause": "",
	"tasktype": "comtwo01,comtwo02,comtwo03,comtwo04,comtwo05,comtwo06",
	"radiosourcenum": "1",
	"relevantdoc": "rd01,rd02,rd04,rd03,rd05",
	"safedistance": "10",
	"issjtssxzy": "",
	"isupgradedh": "",
	"isdzdh": "",
	"isrecord": "",
	"excavation_eqp": "",
	"territorialunitcode": "CS8082020",
	"worker": "",
	"pipeline_level": "",
	"dataStatus": 0,
	"ver": 1,
	"created_by": 1000,
	"created_dt": now,
	"updated_by": 1000,
	"updated_dt": now,
	"df": 0,
	"tenantid": 1,
	"ts": ts,
	"istaskpause": 0,
	"classgroup": "",
	"isend": "",
	"end_reason": "",
	"end_dt": "",
	"groundwire_num": "",
	"groupknife_num": "",
	"groundwire_code": "",
	"othercontent": "",
	"sent_overdueclose_message": 0,
	"isupgrade": "0",
	"isfireday": "0",
	"isdue": "0",
	"operator": "",
	"worktimeconsum": "",
	"device_id": "",
	"task_pause": "0",
	"projecttype": "",
	"is_pause": 0,
	"workticketid": workticketidx,
	"worktaskid": worktaskidx,
	"equipmentnumber": "",
	"worktype": "shex",
	"territorialunitid": 2000000003339,
	"territorialunitname": "运行一部",
	"applyunitid": 2000000003339,
	"applyunitname": "运行一部",
	"worknumber": "",
	"worklevel": "",
	"site": "作业地点123",
	"workway": "",
	"planstarttime": starttime,
	"planendtime": endtime,
	"actualstarttime": "",
	"actualendtime": "",
	"otherwork": "",
	"workname": name,
	"workcontent": "作业内容123",
	"workunit": 1688712,
	"workunitname": "长庆石化分公司",
	"workstatus": "draft",
	"equipmentpipename": "",
	"medium": "",
	"temperature": "",
	"pressure": "",
	"blindplate_material": "",
	"blindplate_spec": "",
	"blindplate_code": "",
	"blindplate_mapandcode": "",
	"workhighly": "",
	"objectmass": "",
	"poweraccesspoint": "",
	"workvoltage": "",
	"equipmentandpower": "",
	"otherunit": "",
	"workreason": "",
	"isharmconfirm": "",
	"ismeasureconfirm": "",
	"isgascomplate": "",
	"issigncomplate": "",
	"created_by_name": "卢健",
	"updated_by_name": "卢健",
	"closereason": "",
	"gastestaging": "",
	"blindplate_worktype": "",
	"gasket_material": "",
	"gasket_spec": "",
	"close_type": "",
	"delaynum": 0,
	"beendelaynum": 0,
	"isppeconfirm": "",
	"invalidreason": "",
	"hassafetyplan": "",
	"hashseplan": "",
	"hasemergencyplan": "",
	"hasdrawpaper": "",
	"haschecklist": "",
	"hasrescueplan": "",
	"loadradius": "",
	"loaddegree": "",
	"loadrate": "",
	"objectnorm": "",
	"loadmass": "",
	"haslineopensitemap": "",
	"radiosourcetype": "1",
	"sourcecode": "22",
	"sourcestrength": "2",
	"suprange": "12",
	"controlrange": "2",
	"drawshow": "",
	"hashookcheck": "",
	"hasfacadecheck": "",
	"hasdrivermedical": "",
	"objectname": "",
	"cancelreason": "",
	"hidesituation": "",
	"work_position_id": 2000000002019,
	"isgas_detection": 0,
	"gas_aging": "",
	"isqualgasdetection": "",
	"dig_size_l": "",
	"dig_size_w": "",
	"dig_size_h": "",
	"attaches": "",
	"lock_status": 0,
	"lock_equipment_id": "",
	"dl_uuid": "",
	"dl_time": "",
	"level_upgrade": 0,
	"loadgoodsname": "",
	"loadhigh": "",
	"worktask_name": name,
	"worktype_name": "射线作业",
	"dz_craneno": "",
	"gas_standard_type": "",
	"isproprietor": "",
	"worksite": "",
	"workticketmbcdid": "",
	"isstoppower": "",
	"work_position_name": "制氢北区",
	"gas_detector_no": "",
	"additional_requirements": "",
	"worklevel_org": ""
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuit.append(caseinfo.copy())
#pc全票全
'''