#手机端主流程全票-作业处理-其他操作（PC预约）

from case.case2 import *

#用例信息变量定义
testsuitm35 = []
caseinfo = {}
caseinfo['id'] = 1
caseinfo['name'] = ''
caseinfo['result'] = ""
caseinfo['url'] = ''
caseinfo['data'] = ''
caseinfo['sign'] =''
caseinfo['flag'] = ''
caseinfo['isactive'] = ''

#作业处理-用火作业
workticketidx  = workticketid +3
caseinfo['id'] = 3401
caseinfo['name'] = '作业处理-用火作业-气体复测'
#http://192.168.6.156/m/hse_m/HSE_WORKTASK_INJOB_M/gasAudit.json?workticketid=2000000003772&workType=dh&worklevel=gb_dh_workLevel01&datatype=gas&businesstype=&detectiontype=retest
url = 'http://192.168.6.156/m/hse_m/HSE_WORKTASK_INJOB_M/gasAudit.json?workticketid=%d&workType=dh&worklevel=gb_dh_workLevel01&datatype=gas&businesstype=&detectiontype=retest'%(workticketidx)

data = {
	"unCompleteStaticValueList": [{
		"downlimit": 0,
		"groupType": "3",
		"code": "combustible",
		"isincludeboundary": 1,
		"preValue": "0.1",
		"name": "可燃气",
		"dataStatus": 0,
		"value": "0.1",
		"isShow": 1,
		"upperlimit": 0.5
	}, {
		"code": "detectiontype",
		"value": "audit"
	}, {
		"code": "gasdetectionid",
		"value": ""
	}, {
		"code": "analysisname",
		"value": "作业地点"
	}, {
		"code": "part",
		"value": "炼油北区"
	}, {
		"code": "workticketid",
		"value": workticketidx
	}, {
		"code": "detectiontime",
		"value": now
	}, {
		"code": "iscomplete",
		"value": "0"
	}, {
		"code": "created_by",
		"value": ""
	}, {
		"code": "created_dt",
		"value": ""
	}, {
		"code": "updated_by",
		"value": 2000000012062
	}, {
		"code": "updated_dt",
		"value": ""
	}, {
		"code": "tenantid",
		"value": 2000000001003
	}, {
		"code": "remark",
		"value": ""
	}],
	"mainAttributeVO": {
		"cardnum": "16143013651646800519",
		"saveApprvoalInfo": "true",
		"person_type": "orgperson",
		"idnumber": "",
		"busdata": {
			"cardnum": "16143013651646800519",
			"person_type": "orgperson",
			"dataStatus": 0,
			"personid": 2000000016201,
			"person_name": "赵成"
		},
		"person_name": "赵成",
		"personid": 2000000016201,
		"specialworktype": "",
		"uuid": "1592961806701"
	},
	"auditPlainLineList": [{
		"actiontype": "card",
		"isexmaineable": 1,
		"groupType": "4",
		"code": "2000000007454",
		"personList": [{
			"cardnum": "16143013651646800519",
			"saveApprvoalInfo": "true",
			"person_type": "orgperson",
			"idnumber": "",
			"busdata": {
				"cardnum": "16143013651646800519",
				"person_type": "orgperson",
				"dataStatus": 0,
				"personid": 2000000016201,
				"person_name": "赵成"
			},
			"person_name": "赵成",
			"personid": 2000000016201,
			"specialworktype": "",
			"uuid": "1592961806701"
		}],
		"idnumber": "",
		"dataStatus": 0,
		"ismustaudit": 1,
		"force_photo": 1,
		"isEnd": 1,
		"ismulti": 0,
		"isShow": 1,
		"auditorder": 5,
		"isinputidnumber": 0,
		"name": "分析人",
		"audittype": "card",
		"specialworktype": "",
		"value": "",
		"isbrushposition": 1,
		"disporder": 5
	}]
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuitm35.append(caseinfo.copy())


#作业处理
caseinfo['id'] = 3402
caseinfo['name'] = '作业处理-用火作业-气体复测'
#http://192.168.6.156/m/hse_m/HSE_WORK_APPOINTAUDIT_M/cardSave.json
url = 'http://192.168.6.156/m/hse_m/HSE_WORK_APPOINTAUDIT_M/cardSave.json'
data = {
	"add_attachs": [],
	"del_attachs": [],
	"vo": {
		"equt_name": "",
		"df": 0,
		"code": "",
		"workname": "作业任务名称",
		"territorialdeviceid": 2000000005070,
		"workunitname": "炼油一部",
		"appointendtime": endtime,
		"wf_instance": "",
		"iscontainfireday": "",
		"worktaskid_no": 0,
		"work_position_name": "脱硫区",
		"wf_current_user": "",
		"plantype": "",
		"wf_audit_time": "",
		"tableName": "hse_work_appoint",
		"iscontractor": "0",
		"insert__": "37c2f7d31a534c17b0ef26901d0f9e3a",
		"territorialunitid": 2000000005066,
		"territorialdevicename": "脱硫装置",
		"tenantid": 2000000001003,
		"territorialunitname": "炼油一部",
		"equipmentnumber": "",
		"ver": 1,
		"created_dt": now,
		"appointstarttime": starttime,
		"wf_current_nodeid": "",
		"worktype": "dh,sx,mbcd,gc,dz,lsyd,dt",
		"dataStatus": 0,
		"work_appoint_id": "",
		"standardmaintenance": "",
		"wf_type": "",
		"work_position_id": 2000000001499,
		"wf_create_user": "",
		"territorialdevicecode": "0000000103000008",
		"workunit": 2000000005066,
		"updated_dt": now,
		"worksite": "北京",
		"territorialunitcode": "000000010300",
		"workcontent": "",
		"status": "draft",
		"wf_audit_state": ""
	}
}
caseinfo['url'] = url
caseinfo['data'] =data
#testsuitm35.append(caseinfo.copy())

#作业处理
workticketidx = workticketid + 3
caseinfo['id'] = 3403
caseinfo['name'] = '作业处理-用火作业-监护记录-作业前检查'
#http://192.168.6.156/m/hse_m/HSE_CHECK_BEFORE_M/confirmCheckBefore.json?workticketid=2000000003772
url = 'http://192.168.6.156/m/hse_m/HSE_CHECK_BEFORE_M/confirmCheckBefore.json?workticketid=%d'%(workticketidx)
data = {
	"mainAttributeVO": {},
	"auditPlainLineList": [{
		"actiontype": "sign",
		"isexmaineable": 1,
		"groupType": "4",
		"code": "2000000007685",
		"idnumber": "",
		"dataStatus": 0,
		"ismustaudit": 1,
		"force_photo": 0,
		"isEnd": 0,
		"ismulti": 1,
		"isShow": 1,
		"auditorder": 17,
		"isinputidnumber": 0,
		"electronicSignature": [{
			"imgStr": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAesSURBVHic7d07i15VFAbgHWdUUBAhgrfSwkAEUTSiNkZEC61FLLTQykb/hZUW1t4a\nwRTBSkS0sLNSI0lvIYgwkkbUmJAZi4Awc1Z0ZnL2beV54GtW9VYfL2evfU4pAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALucKKVslVJO\n9Q4CAOT0eCllZ88P6ORI7wAAlUQFw38edHJD7wAAQH4KB5DRPb0DAAD5fVyW+xuf9QwEAOSzt2zs\nlFKOdU0E1zkLVEBGFkZhMHY4gGzu6h0AAMjvvbI8TjndNREAkM7lsiwcj3RNBDjTBNKxvwEDssMB\nZLLZOwAQUziATN4KZmeapwAAUtsqy/2Nl7omAkopzjWBXOxvwKAcqQAA1SkcQBbPBrMLzVMAAKl9\nVZb7G293TQQApBN9sO1o10TAvyxTAVlYGIWB2eEAMvAkAwCo7p2yPE75vGsiACCdS2VZOE52TQTs\n4nwTyMD+BgzODgcAUJ3CAczu1WD2S/MUAEBqZ8tyf+PNromABWecwOyi/Y2NUsp26yDA1SkcwOws\njMIE7HAAM3uodwAAIL9PynJ/44OuiQCAdKIPth3rmggIOecEZmZ/AyZhhwOY1WbvAMD+KRzArN4I\nZmeapwAAUvupLPc3XumaCLgqZ53ArOxvwEQcqQAA1SkcwIweDGZeZQ4DUziAGUULox82TwEApHa5\nLBdGH+6aCPhPFqyAGVkYhck4UgEAqlM4gNk8Fcz+ah0CAMjt07Lc33i3ayIAIJ3oC7H3d00E/C9L\nVsBsLIzChOxwAADVKRzATB4NZpeapwAOTOEAZvJaMPuoeQoAILWLZbkweqJrImBfLFoBM7EwCpNy\npAIAVKdwALO4vXcA4PAUDmAWrwezL5unAABS+7EsF0Zf7poI2DfLVsAsooXRjVLKdusgwMEpHMAs\n3FCBidnhAACqUziAGTwWzM43TwEcmsIBzODFYHaqeQoAILWfy/KGysmuiYADsXAFzMDCKEzOkQoA\nUJ3CAQBUp3AAo4tuqGw1TwFcE4UDGN0Lwex08xQAQGrfl+UNlee7JgIA0tlbNnbKlW+oABNxrQwY\nnSuxkIAdDgCgOoUDAKhO4QBG9lwwO9c8BXDNFA5gZM8Esy+apwAAUvuuLG+oRE89AAAOzZVYSMLV\nMmBkrsRCEnY4AIDqFA4AoDqFAxjVncHscvMUwCoUDmBUTwezr5unAFahcACjejKYfdM6BLAOhQMY\n1RPB7NvmKQCA1KJ3cGx2TQQcmvvswKi8gwMScaQCAFSncAAA1SkcAEB1CgcwovuC2VbzFMBqFA5g\nRMeD2Q/NUwCrUTiAET0QzM41TwGsRuEARqRwQDIKBzAihQMAqG67LN8yemPXRMA18dY+YETeMgrJ\nOFIBAKpTOACA6hQOAKA6hQMAqE7hAACqUzgAgOoUDmA00f/SdvMUwKoUDmA09wazX5unAFalcACj\nuTuYKRwwOYUDGI3CAQkpHMBo7ghmvzVPAaxK4QBGc3Mw+7t5CmBVCgcwmpuCmcIBk1M4gNFEheNC\n8xTAqhQOYDSecEBCCgcwGjsckJDCAYzGEw5ISOEARmOHAxJSOIDReMIBCSkcwGguBrOohAATUTiA\n0fwZzG5tngJYlcIBjCYqHLc0TwGsSuEARvNHMPOEAyancACj8YQDElI4gNF4wgEJKRzAaDzhgIQU\nDmA0bqlAQgoHMJrfg9ltzVMAq1I4gNGcD2ZHm6cAVqVwAKNROACA6jZKKTvBD5jYkd4BAAJRwfB/\nBRNzpAIAVKdwAADVKRwAQHUKBwBQncIBAFSncAAA1SkcAEB1CgcAUJ3CAQBUp3AAANUpHABAdQoH\nAFCdwgEAVKdwACN6v3cAAOD6cLZc+Uz9TinleOcsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBu/wD+GNrYaL5hAgAAAABJRU5ErkJggg==\n",
			"uuid": ""
		}],
		"name": "监护人确认",
		"audittype": "sign,localaccount,card,signandcard,passward",
		"specialworktype": "",
		"value": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAesSURBVHic7d07i15VFAbgHWdUUBAhgrfSwkAEUTSiNkZEC61FLLTQykb/hZUW1t4a\nwRTBSkS0sLNSI0lvIYgwkkbUmJAZi4Awc1Z0ZnL2beV54GtW9VYfL2evfU4pAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALucKKVslVJO\n9Q4CAOT0eCllZ88P6ORI7wAAlUQFw38edHJD7wAAQH4KB5DRPb0DAAD5fVyW+xuf9QwEAOSzt2zs\nlFKOdU0E1zkLVEBGFkZhMHY4gGzu6h0AAMjvvbI8TjndNREAkM7lsiwcj3RNBDjTBNKxvwEDssMB\nZLLZOwAQUziATN4KZmeapwAAUtsqy/2Nl7omAkopzjWBXOxvwKAcqQAA1SkcQBbPBrMLzVMAAKl9\nVZb7G293TQQApBN9sO1o10TAvyxTAVlYGIWB2eEAMvAkAwCo7p2yPE75vGsiACCdS2VZOE52TQTs\n4nwTyMD+BgzODgcAUJ3CAczu1WD2S/MUAEBqZ8tyf+PNromABWecwOyi/Y2NUsp26yDA1SkcwOws\njMIE7HAAM3uodwAAIL9PynJ/44OuiQCAdKIPth3rmggIOecEZmZ/AyZhhwOY1WbvAMD+KRzArN4I\nZmeapwAAUvupLPc3XumaCLgqZ53ArOxvwEQcqQAA1SkcwIweDGZeZQ4DUziAGUULox82TwEApHa5\nLBdGH+6aCPhPFqyAGVkYhck4UgEAqlM4gNk8Fcz+ah0CAMjt07Lc33i3ayIAIJ3oC7H3d00E/C9L\nVsBsLIzChOxwAADVKRzATB4NZpeapwAOTOEAZvJaMPuoeQoAILWLZbkweqJrImBfLFoBM7EwCpNy\npAIAVKdwALO4vXcA4PAUDmAWrwezL5unAABS+7EsF0Zf7poI2DfLVsAsooXRjVLKdusgwMEpHMAs\n3FCBidnhAACqUziAGTwWzM43TwEcmsIBzODFYHaqeQoAILWfy/KGysmuiYADsXAFzMDCKEzOkQoA\nUJ3CAQBUp3AAo4tuqGw1TwFcE4UDGN0Lwex08xQAQGrfl+UNlee7JgIA0tlbNnbKlW+oABNxrQwY\nnSuxkIAdDgCgOoUDAKhO4QBG9lwwO9c8BXDNFA5gZM8Esy+apwAAUvuuLG+oRE89AAAOzZVYSMLV\nMmBkrsRCEnY4AIDqFA4AoDqFAxjVncHscvMUwCoUDmBUTwezr5unAFahcACjejKYfdM6BLAOhQMY\n1RPB7NvmKQCA1KJ3cGx2TQQcmvvswKi8gwMScaQCAFSncAAA1SkcAEB1CgcwovuC2VbzFMBqFA5g\nRMeD2Q/NUwCrUTiAET0QzM41TwGsRuEARqRwQDIKBzAihQMAqG67LN8yemPXRMA18dY+YETeMgrJ\nOFIBAKpTOACA6hQOAKA6hQMAqE7hAACqUzgAgOoUDmA00f/SdvMUwKoUDmA09wazX5unAFalcACj\nuTuYKRwwOYUDGI3CAQkpHMBo7ghmvzVPAaxK4QBGc3Mw+7t5CmBVCgcwmpuCmcIBk1M4gNFEheNC\n8xTAqhQOYDSecEBCCgcwGjsckJDCAYzGEw5ISOEARmOHAxJSOIDReMIBCSkcwGguBrOohAATUTiA\n0fwZzG5tngJYlcIBjCYqHLc0TwGsSuEARvNHMPOEAyancACj8YQDElI4gNF4wgEJKRzAaDzhgIQU\nDmA0bqlAQgoHMJrfg9ltzVMAq1I4gNGcD2ZHm6cAVqVwAKNROACA6jZKKTvBD5jYkd4BAAJRwfB/\nBRNzpAIAVKdwAADVKRwAQHUKBwBQncIBAFSncAAA1SkcAEB1CgcAUJ3CAQBUp3AAANUpHABAdQoH\nAFCdwgEAVKdwACN6v3cAAOD6cLZc+Uz9TinleOcsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBu/wD+GNrYaL5hAgAAAABJRU5ErkJggg==\n",
		"isbrushposition": 0,
		"disporder": 17
	}],
	"voList": {
		"is_org_qualified_label": "1",
		"base_equt_check": "",
		"access_card_num": "2",
		"df": 0,
		"custody_certificate_num": "",
		"base_huan_check": "",
		"gas_alarm": "alarm_a,alarm_b",
		"is_safety_belt_qualified": "1",
		"base_jiju_check": "",
		"created_by_name": "",
		"is_mbcd_reg_tab": "",
		"updated_by_name": "",
		"base_self_check": "",
		"is_mbcd_location_img": "",
		"is_dress_code": "1",
		"id": "",
		"is_safety_helmet_qualified": "1",
		"video_monitor_num": "2",
		"sxkj_harm_medium": "medium_a",
		"workticket_measure_num": "",
		"special_workticket_card_num": "2",
		"is_eq_has_cbs_label": "1",
		"created_dt": now,
		"nearest_eq": "10",
		"work_type": "dh",
		"secondary_safety_education_num": "2",
		"created_by": "",
		"impl_measure_num": "5",
		"base_chat": "",
		"is_confirm": "",
		"nearest_eq_name": "",
		"updated_dt": now,
		"work_personnel_num": "2",
		"updated_by": "",
		"base_person_check": "",
		"workticketid": workticketidx
	}
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuitm35.append(caseinfo.copy())

#作业处理
workticketidx = workticketid + 3
caseinfo['id'] = 3404
caseinfo['name'] = '作业处理-用火作业-监护记录-作业过程'
#http://192.168.6.156/m/hse_m/HSE_MONITOR_PROCESS_M/confirmMonitorProcess.json?workticketid=2000000003772
url = 'http://192.168.6.156/m/hse_m/HSE_MONITOR_PROCESS_M/confirmMonitorProcess.json?workticketid=%d'%(workticketidx)
data = {
	"mainAttributeVO": {},
	"auditPlainLineList": [{
		"actiontype": "sign",
		"isexmaineable": 1,
		"groupType": "4",
		"code": "2000000007686",
		"idnumber": "",
		"dataStatus": 0,
		"ismustaudit": 1,
		"force_photo": 0,
		"isEnd": 1,
		"ismulti": 0,
		"isShow": 1,
		"auditorder": 18,
		"isinputidnumber": 0,
		"electronicSignature": [{
			"imgStr": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAmjSURBVHic7d1PqKdlFQfwc2ecmcwSjFRuFIlKEYEgxEBS9hdaVFLSSqhFta1FLm1R\nBNEmgjYt2ihGBbUJZChaKRG4KIxEC3JaBeYYDYR/hjvObTHwm8b33IXTfZ7zu+f9fOBuzuq7mPnx\n5TnP+74RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAUfbNiNj/n79jtXEAgG524+qysR8RZ0oTAQDtvL5s7EfE\nC6WJAIBWHo+8cHysMhQA0MfpyMvG+cpQ8P/aqQ4AwFX2D5j7veZIc+MZYHu8csD8C1NTAABtfTfy\nVcrZylAAQB8nIy8bB61XAADesL3Iy8atlaEAgD6+GHnZ+H5lKDhsbj0D1MrWJl5jTjv+QQPU+cUB\n8xunpgAAWstWKb8rTQQAtPL38FQKADDQDZGXjYcqQwEAvZwPpxsAwEC3Rl427qsMBaN5LBZgrosR\ncTyZ+z2mNY/FAsxze+Rl467ZQQCAvi7FcpVysTQRANDKnZHf3XhXZSgAoJfXYlk2XilNBAC08u7I\nTzd2K0MBAL1ciGXZuFCaCABo5e3hdAMAGOzlWJaNvdJEAEAr10d+unFnZSgAoJfsi7CXShMBAO1k\npxsfKE0EALTyWPgiLAAwWFY2vlKaCABo5cFwugEADJaVjR+XJgIAWrkjnG4AAIO9FMuy8VxpIgCg\nnex048bSRABAKz8L6xQAYLCsbDxQmggAaOXj4XQDABhsL5Zl40xpItgiO9UBAJrITjOOh4+1QURE\nHKsOANDAw8nMl2EBgEOV3d34fGkiAKCV94TLogDAYOdiWTaeLE0EALSTnW7cUJoIAGjla2GdAgAM\nlpWNb5cmgi3lPRwA12Yn8sde/a5Cwns4AK7No8lsb3oKAKC1bJ3ymdJEAEArt4TLogDAYH+IZdl4\ntjQRANBOdrrxjtJEAEAr94R1CgAw2POxLBs/L00EALSTnW6cKE0EALRinQIADJetUx6uDAQA9GOd\nAgAMZZ0CAAxnnQIADGedAgAM9cGwTgEABsvWKY+UJgIA2rFOAQCG2g3rFABgsDOxLBtnShMBAO1k\npxu7pYngCNqpDgCwxXYi4tIBc+ANOFYdAGCLfSeZ/Wt6CgCgtWydcl9pIjiiHAsCHCx7GsXvJlwD\nKxWA3P3VAQCA/l6M5TrlW5WB4ChzNAiQs06BQ2SlArB0c3UAAKC/R8LbRQGAwbLHYd9fmgiOOPtI\ngCX3N+CQucMBcLVPVgcAAPp7KpbrlO+VJgIA2snub5wqTQQN2EkCXM39DRjAHQ6AK76RzM5NTwEA\ntPZqLNcpD5QmgiYcEwJcYZ0Cg1ipAFzmdeYAwHA/iuU65deliQCAdrLHYU+XJoJG7CYBLnN/AwZy\nhwMg4m3VAQCA/n4Qy3XKb0sTAQDtvBbLwvGh0kTQjP0kgPsbMJw7HMDavaU6AKyBwgGs3UPJ7Inp\nKQCA1vZieX/jE6WJoCE7SmDt3N+ACaxUgDV7U3UAWAuFA1izryezJ6enAABaezGW9zfuL00ETdlT\nAmvm/gZMYqUCAAyncABrlX16/uL0FABAaz+N5f2NH5YmAgDaeX3Z2I+I20sTQWMuRwFr5cIoTOQO\nB7BGfvtgMv/pgDX6ajL78/QUAEBrz8Ty/saXSxNBc/aVwBq5vwGTWakAAMMpHMDa7FYHgDVSOIC1\n+VIy+9X0FABAa0+HL8TCdC5JAWvjwigUsFIBAIZTOACA4RQOYE0+ncz+Nj0FrJDCAaxJ9oTKo9NT\nAACtZZ+kv60yEKyFm9nAmnhCBYpYqQAAwykcwFrclswuzQ4Ba6VwAGuRXRj95fQUAEBrf4zlhdHP\nlSYCANrJnlA5XpoIVsTtbGAtPKEChdzhAACGUzgAgOEUDmANPpXMnpmeAlZM4QDWIPto22PTUwAA\nrZ2N5RMqHy5NBCvjhjawBp5QgWJWKgDAcAoHADCcwgF0d6o6AKBwAP1l30t5YnoKWDmFA+ju3mT2\nm+kpAIDWnorlI7EfrQwEAPSTfSX2utJEsEKeQwe68w4O2ALucAAAwykcAMBwCgcAMJzCAXR2VzL7\nx/QUgMIBtHZPMvv99BSAwgG0pnAAAMM9F8t3cJwuTQQr5Vl0oLPsHRzHDpgDA1mpAGujbEABhQMA\nGE7hAACGUzgAgOEUDqCrE9UBgCsUDqCru5PZs9NTABGhcAB9Za81/9P0FEBEKBxAX+9LZk9PTwFE\nhMIB9PXeZPbX6SmAiFA4gL6ywvGX6SmAiPBqc6AvrzWHLeKEA1gTZQOKKBwAwHAKBwAwnMIBAAyn\ncAAAwykcAMBwCgcAMJzCAXR0MpldmJ4C2FA4gI5uSWbnpqcANhQOoKObk9kL01MAGwoH0JHCAVtG\n4QA6UjhgyygcQEdvTWb/mZ4C2FA4gI7enMxemp4C2FA4gI6uT2YvT08BbCgcQEfZCYfCAYUUDqCj\nU8nMi7+gkMIBdLSXzE5MTwFsKBxARxeT2XXTUwAbCgfQUVY4nHBAIYUD6OjVZHbT9BTAhsIBdPR8\nMss+6AZMonAAHf0zmSkcUEjhADrKCsc7p6cAAFo7GRH7yR9QZKc6AMAgWcHwmwdFrFQAgOEUDgBg\nOIUDABhO4QC6+ncyu2N6CiAiFA6gr8eT2b3TUwARoXAAfWWF4yPTUwAArd0dy/dwnC1NBCvmmXSg\nM+/igC1hpQIADKdwAADDKRwAwHAKB9DZ+eoAAEB/2ZMqAACH7rNx+aTjJ9VBAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAOEz/BSxWKTBG5bf8AAAAAElFTkSuQmCC\n",
			"uuid": ""
		}],
		"name": "监护人",
		"audittype": "sign",
		"specialworktype": "",
		"value": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAmjSURBVHic7d1PqKdlFQfwc2ecmcwSjFRuFIlKEYEgxEBS9hdaVFLSSqhFta1FLm1R\nBNEmgjYt2ihGBbUJZChaKRG4KIxEC3JaBeYYDYR/hjvObTHwm8b33IXTfZ7zu+f9fOBuzuq7mPnx\n5TnP+74RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAUfbNiNj/n79jtXEAgG524+qysR8RZ0oTAQDtvL5s7EfE\nC6WJAIBWHo+8cHysMhQA0MfpyMvG+cpQ8P/aqQ4AwFX2D5j7veZIc+MZYHu8csD8C1NTAABtfTfy\nVcrZylAAQB8nIy8bB61XAADesL3Iy8atlaEAgD6+GHnZ+H5lKDhsbj0D1MrWJl5jTjv+QQPU+cUB\n8xunpgAAWstWKb8rTQQAtPL38FQKADDQDZGXjYcqQwEAvZwPpxsAwEC3Rl427qsMBaN5LBZgrosR\ncTyZ+z2mNY/FAsxze+Rl467ZQQCAvi7FcpVysTQRANDKnZHf3XhXZSgAoJfXYlk2XilNBAC08u7I\nTzd2K0MBAL1ciGXZuFCaCABo5e3hdAMAGOzlWJaNvdJEAEAr10d+unFnZSgAoJfsi7CXShMBAO1k\npxsfKE0EALTyWPgiLAAwWFY2vlKaCABo5cFwugEADJaVjR+XJgIAWrkjnG4AAIO9FMuy8VxpIgCg\nnex048bSRABAKz8L6xQAYLCsbDxQmggAaOXj4XQDABhsL5Zl40xpItgiO9UBAJrITjOOh4+1QURE\nHKsOANDAw8nMl2EBgEOV3d34fGkiAKCV94TLogDAYOdiWTaeLE0EALSTnW7cUJoIAGjla2GdAgAM\nlpWNb5cmgi3lPRwA12Yn8sde/a5Cwns4AK7No8lsb3oKAKC1bJ3ymdJEAEArt4TLogDAYH+IZdl4\ntjQRANBOdrrxjtJEAEAr94R1CgAw2POxLBs/L00EALSTnW6cKE0EALRinQIADJetUx6uDAQA9GOd\nAgAMZZ0CAAxnnQIADGedAgAM9cGwTgEABsvWKY+UJgIA2rFOAQCG2g3rFABgsDOxLBtnShMBAO1k\npxu7pYngCNqpDgCwxXYi4tIBc+ANOFYdAGCLfSeZ/Wt6CgCgtWydcl9pIjiiHAsCHCx7GsXvJlwD\nKxWA3P3VAQCA/l6M5TrlW5WB4ChzNAiQs06BQ2SlArB0c3UAAKC/R8LbRQGAwbLHYd9fmgiOOPtI\ngCX3N+CQucMBcLVPVgcAAPp7KpbrlO+VJgIA2snub5wqTQQN2EkCXM39DRjAHQ6AK76RzM5NTwEA\ntPZqLNcpD5QmgiYcEwJcYZ0Cg1ipAFzmdeYAwHA/iuU65deliQCAdrLHYU+XJoJG7CYBLnN/AwZy\nhwMg4m3VAQCA/n4Qy3XKb0sTAQDtvBbLwvGh0kTQjP0kgPsbMJw7HMDavaU6AKyBwgGs3UPJ7Inp\nKQCA1vZieX/jE6WJoCE7SmDt3N+ACaxUgDV7U3UAWAuFA1izryezJ6enAABaezGW9zfuL00ETdlT\nAmvm/gZMYqUCAAyncABrlX16/uL0FABAaz+N5f2NH5YmAgDaeX3Z2I+I20sTQWMuRwFr5cIoTOQO\nB7BGfvtgMv/pgDX6ajL78/QUAEBrz8Ty/saXSxNBc/aVwBq5vwGTWakAAMMpHMDa7FYHgDVSOIC1\n+VIy+9X0FABAa0+HL8TCdC5JAWvjwigUsFIBAIZTOACA4RQOYE0+ncz+Nj0FrJDCAaxJ9oTKo9NT\nAACtZZ+kv60yEKyFm9nAmnhCBYpYqQAAwykcwFrclswuzQ4Ba6VwAGuRXRj95fQUAEBrf4zlhdHP\nlSYCANrJnlA5XpoIVsTtbGAtPKEChdzhAACGUzgAgOEUDmANPpXMnpmeAlZM4QDWIPto22PTUwAA\nrZ2N5RMqHy5NBCvjhjawBp5QgWJWKgDAcAoHADCcwgF0d6o6AKBwAP1l30t5YnoKWDmFA+ju3mT2\nm+kpAIDWnorlI7EfrQwEAPSTfSX2utJEsEKeQwe68w4O2ALucAAAwykcAMBwCgcAMJzCAXR2VzL7\nx/QUgMIBtHZPMvv99BSAwgG0pnAAAMM9F8t3cJwuTQQr5Vl0oLPsHRzHDpgDA1mpAGujbEABhQMA\nGE7hAACGUzgAgOEUDqCrE9UBgCsUDqCru5PZs9NTABGhcAB9Za81/9P0FEBEKBxAX+9LZk9PTwFE\nhMIB9PXeZPbX6SmAiFA4gL6ywvGX6SmAiPBqc6AvrzWHLeKEA1gTZQOKKBwAwHAKBwAwnMIBAAyn\ncAAAwykcAMBwCgcAMJzCAXR0MpldmJ4C2FA4gI5uSWbnpqcANhQOoKObk9kL01MAGwoH0JHCAVtG\n4QA6UjhgyygcQEdvTWb/mZ4C2FA4gI7enMxemp4C2FA4gI6uT2YvT08BbCgcQEfZCYfCAYUUDqCj\nU8nMi7+gkMIBdLSXzE5MTwFsKBxARxeT2XXTUwAbCgfQUVY4nHBAIYUD6OjVZHbT9BTAhsIBdPR8\nMss+6AZMonAAHf0zmSkcUEjhADrKCsc7p6cAAFo7GRH7yR9QZKc6AMAgWcHwmwdFrFQAgOEUDgBg\nOIUDABhO4QC6+ncyu2N6CiAiFA6gr8eT2b3TUwARoXAAfWWF4yPTUwAArd0dy/dwnC1NBCvmmXSg\nM+/igC1hpQIADKdwAADDKRwAwHAKB9DZ+eoAAEB/2ZMqAACH7rNx+aTjJ9VBAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAOEz/BSxWKTBG5bf8AAAAAElFTkSuQmCC\n",
		"isbrushposition": 0,
		"disporder": 18
	}],
	"voList": {
		"df": 0,
		"base_person_inout": "",
		"record_dt": now,
		"tool_in_num": "",
		"eq_run_state": "",
		"created_by_name": "",
		"eq_exceptiton_desc": "",
		"is_pro_env_change": "1",
		"updated_by_name": "",
		"video_monitor_state": "1",
		"tool_out_num": "",
		"id": "",
		"mbcd_num": "",
		"pro_env_exception_desc": "",
		"created_dt": now,
		"base_change": "",
		"dh_position": "",
		"personnel_exit_num": "",
		"work_type": "dh",
		"base_huanjing": "",
		"created_by": "",
		"gas_record": [{
			"code": "Carbonmonoxide",
			"value": "0.1"
		}],
		"is_confirm": "",
		"video_monitor_exception_desc": "",
		"eq_remnant_medium": "",
		"updated_dt": now,
		"updated_by": "",
		"workticketid": workticketidx,
		"personnel_access_num": ""
	}
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuitm35.append(caseinfo.copy())

#作业处理
workticketidx = workticketid + 3
caseinfo['id'] = 3405
caseinfo['name'] = '作业处理-用火作业-监护记录-上级检查'
#http://192.168.6.156/m/hse_m/HSE_SUPERIOR_INSPECTION_M/confirmSuperiorInspectAudit.json
url = 'http://192.168.6.156/m/hse_m/HSE_MONITOR_PROCESS_M/confirmMonitorProcess.json?workticketid=%d'%(workticketidx)
data = {
	"mainAttributeVO": {},
	"auditPlainLineList": [{
		"actiontype": "sign",
		"isexmaineable": 1,
		"groupType": "4",
		"code": "2000000007687",
		"idnumber": "",
		"dataStatus": 0,
		"ismustaudit": 1,
		"force_photo": 0,
		"isEnd": 1,
		"ismulti": 0,
		"isShow": 1,
		"auditorder": 19,
		"isinputidnumber": 0,
		"electronicSignature": [{
			"imgStr": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAtlSURBVHic7d1bqG1lGQbgd2+tULOD2tZdZhRBRJYVaEllbjUqKoxOEGmHiyiyLESi\nqDA6UHQStC4iLawooqQuzKyLrIuyg0JBmiCUeUgjT6WyO21XF0vJ9vrnHHMt15jfGr/PA4MF42LP\ndyxYe7x8/z/HSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADu7+QkP0qy\nsoHjq0mOW35kAGCr+2Q2Vi4WOX6RZMfyLgUA2EpekvFKxqzj50u5MgCg3ElZftHY+7hy9KsEAErs\nn2R36svG/Y/zR71iAGCpvp31FYHbk3wuyVEb+KxXJLliHZ+1e4PXBABsIX/LYjf+T430+Rcu+PlP\nG+nzAYARHZjhm/wlS8zz+gXy7FpiHgDgAdqe+Tf2G+ui5b1zcq0keVFdNABgPbb60sX2JHsyO+Mx\nddEAgEXcntk38q3m8szOul9hLgBgjjPTvnn/uzLUgF9lOgUJAMh0b9w/STv3XYWZAICG16R90z6g\nMtQ63BGbSAFgy7s2a2/W368MtAFTndAAwINGDzfq/dO+judVhgIA/qeHwpGsvlG2l2sBCm2rDgCd\nat2Up/j3ti3JPTPOAyxse3UAYEubNc14w1JTAABNPS1DnJW11/KX0kTA5BiLwjh6WVK5T2/XAyyZ\nJRUAYHQKB7CI3Y1zz156CmCyFA5gEV9rnDt+2SGA6VI4gEX8pHHu+CVnAAD20tO3VJJkZ9Zez92l\niQCANTfnS2rjbIreShQATN4Z6e/GrHAAG+Z79MCiPIsD2DCbRgGA0SkcAMDoFA4AYHQKBwAwOoUD\nABidwgEAjE7hAABGp3AAAKNTOACA0SkcwCL2bZzzaHNgYQoHsIhjGud+u/QUwGQpHMAidjXOXb70\nFABA167P2jfFnlCaCJgUb3oEFuFNscADYkkFABidwgEMeWx1AGD6FA5gyDsb57679BQAQNf23iy6\nkuSlpYmAybHpCxhiwyjwgFlSAeY5qToAANC/q7N2OeXc0kQAQHda+zceWpoIAOjK4WkXDgCATXNl\n1paNK0oTAQDdaU03dpQmAgC6ckIspwAAI7sza8vGt0oTAZPm4T1Ai4d9AZvKg7+AvX20OgAA0L/W\n3o2zShMBAF15amwWBQBGdnfWlo3rShMBAF3ZnvZ046DKUABAXy6N5RQAYGStsvHK0kQAQFc+E9MN\nAGBkrbJxdmkiAKArp8R0AwAYWats/LQ0EQDQlSPTLhzemwIAbJpW2fhTaSIAoCs70y4c+1WGAgD6\n0iobu0sTAQBdeVTaheOQylAAQF/uytqy8c/SRABAVw5Oe7pxRGUoAKAvu7O2bOwpTQQAdOXQtKcb\nT6oMBQD05T9ZWzb+U5oIAOjK09OebhxeGQoA6EurbNxVmggA6Mr70i4cB1SGAgD60iob15QmAgC6\n8ou0CwcAwKZplY0vlyYCALpyd0w3AIARPSvtsvG6ylDAg9O26gDAaGZNMvzdA0u3vToAMIr3zDi/\nY6kpAICutZZSbixNBAB05XtpFw5LKQDApmmVjYtKEwEAXbk6vgYLAIxon7TLxgcqQwEAfbk5phsA\nwIgOSLtsnFoZCgDoy99jugEAjGhb2mXjxMpQAEBffhjTDQBgZK2y8ZbSRABAV06L6QYAMLJW2big\nNBFAg3crwLS1phn+roEtx+vpYbrOaZyznAIAbKrWcsobSxMBzGD0CtNlOQWYDEsqME2tScaepacA\nALp2XdYup7y/NBHAHMavME2WU4BJsaQCAIxO4QAARqdwAACjUzgAgNEpHADA6BQOAGB0Cgf044vV\nAQCAvpye9rtUflgZCgDoT6tw3HccVZgLAOjI2zO/dKwkObEsHQDQjc9muHSsJDm7KiAA0IddWax0\nrCS5PsmxNTEBgB7ckMWLx0pW3zj73JKkAMCkPTzJHVlf8VhJ8q8kn0/y5OVHBgCm6qFJfpX1F4/7\nH9cm+XSS5yw3OgAwRR/JAyseex83J7kgyduSHLnE6wAmbFt1AGBpnpjkS1neV2Vvzeq+kuvv/Xnj\nveduTXLLvT//muTPS8oDACzZtiQfTnJPNnf6sZnH1UnOS/Lm2FsCAN14d1b3bVQXjfUs7XwzyatH\n+F0AAEvylCQfy+rXZ6vLxaLHtVl9LgkAMHEnJ/l4kkuT7E59yZh1nDzWLwBYP5tGgbEckeRxSQ6/\n9+dhSQ5JcnCSg5IcmmRHkkePmOHyJEeP+O8DC1I4gK1ovyTHJ3l+khdk9XHs+27w37o5yc7NiQUA\nPNi8PMn5Se7K8PLKgUUZAYDOHJjkmrQLxzcKcwEAHXpC1haOG0sTAfZwAF1aaZzz/x0U2l4dAGCT\nHds4d9XSUwAAXftx1i6pfLo0EQDQndam0UeWJgIAuvLCtAsHAMCmaZWNH5QmAgC6clzahcO3UwCA\nTdMqGzeVJgIAuvKttAvHPpWhAIB+HJZ22fh9ZSjg/1nbBKZu1rdQ/P8GW4gnjQJTNmuPxgeXmgIA\n6NYv015KubsyFADQj/PSLhse8gUAbIrzM7tsPKUwFwDQiYszu2y8tjAXANCJyzO7bJxXmAsA6MQd\nmV02Li7MBQB0YlbRWEny9cJcAEAHnpj5ZePsumgAQA8+lvll46S6aABAD27I/LJxcF00AGDqHp75\nRWNPXTQAoAfvyvyycVVdNACgB3/M/LJxel00AGDqdmR+0VhJ8piydADA5H0h84vGbXXRAIAe7M78\nsvHxumgAwNS9KsNLKIeWpQMAJu+mzC8af6yLBgBM3dEZnmqcWpYOAJi832X4QV77lqUDACbtqAxP\nNb5Slg4AmLyhqcZKVp+/AQCwbs/McNH4WVk6AGDyrs1w2XhaVTgAYNpeluGi8ZuydADA5N0eUw0A\nYCQfzHDR+HVZOgBg0g7M6nMzhsrGE6oCAgDT9p0MF40Ly9IBAJP2jAwXjZUkj6wKCABM23UZLhqf\nKEsHAEzamRkuGncm2VYVEACYrkdkseWT11UFBACm7acZLhpXl6UDACbtuCw21Xh8VUAAYLq2ZbEn\nhZ5bFRAAmLbPZrho/D3J9qqAAMB07chiyycvrgoIAEzbZRkuGr8sSwcATNquLDbVOLgqIAAwbTdn\nuGh8qCwdADBp78hw0bilLB0AMGkPSfKPDJeNXVUBAYBp+0SGi8ZlZekAgEl7WJI9GS4bO6sCAgDT\ndk6Gi8aXytIBAJN2QJJ7Mr9o/Cur0w8AgHX7coanGmeUpQMAJu3RWez9JwAAG3JRhsvGm8rSAQCT\ntjPDReO2snQAwORdmuGycUpZOgBg8v6Q+UXjb3XRAIBezCsbby3MBQB0pFU07ixNBAB057H5/7Jx\nWm0cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAgIn5L5BG4zK/zThTAAAAAElFTkSuQmCC\n",
			"uuid": ""
		}],
		"name": "上级检查",
		"audittype": "sign,card",
		"specialworktype": "",
		"value": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAtlSURBVHic7d1bqG1lGQbgd2+tULOD2tZdZhRBRJYVaEllbjUqKoxOEGmHiyiyLESi\nqDA6UHQStC4iLawooqQuzKyLrIuyg0JBmiCUeUgjT6WyO21XF0vJ9vrnHHMt15jfGr/PA4MF42LP\ndyxYe7x8/z/HSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADu7+QkP0qy\nsoHjq0mOW35kAGCr+2Q2Vi4WOX6RZMfyLgUA2EpekvFKxqzj50u5MgCg3ElZftHY+7hy9KsEAErs\nn2R36svG/Y/zR71iAGCpvp31FYHbk3wuyVEb+KxXJLliHZ+1e4PXBABsIX/LYjf+T430+Rcu+PlP\nG+nzAYARHZjhm/wlS8zz+gXy7FpiHgDgAdqe+Tf2G+ui5b1zcq0keVFdNABgPbb60sX2JHsyO+Mx\nddEAgEXcntk38q3m8szOul9hLgBgjjPTvnn/uzLUgF9lOgUJAMh0b9w/STv3XYWZAICG16R90z6g\nMtQ63BGbSAFgy7s2a2/W368MtAFTndAAwINGDzfq/dO+judVhgIA/qeHwpGsvlG2l2sBCm2rDgCd\nat2Up/j3ti3JPTPOAyxse3UAYEubNc14w1JTAABNPS1DnJW11/KX0kTA5BiLwjh6WVK5T2/XAyyZ\nJRUAYHQKB7CI3Y1zz156CmCyFA5gEV9rnDt+2SGA6VI4gEX8pHHu+CVnAAD20tO3VJJkZ9Zez92l\niQCANTfnS2rjbIreShQATN4Z6e/GrHAAG+Z79MCiPIsD2DCbRgGA0SkcAMDoFA4AYHQKBwAwOoUD\nABidwgEAjE7hAABGp3AAAKNTOACA0SkcwCL2bZzzaHNgYQoHsIhjGud+u/QUwGQpHMAidjXOXb70\nFABA167P2jfFnlCaCJgUb3oEFuFNscADYkkFABidwgEMeWx1AGD6FA5gyDsb57679BQAQNf23iy6\nkuSlpYmAybHpCxhiwyjwgFlSAeY5qToAANC/q7N2OeXc0kQAQHda+zceWpoIAOjK4WkXDgCATXNl\n1paNK0oTAQDdaU03dpQmAgC6ckIspwAAI7sza8vGt0oTAZPm4T1Ai4d9AZvKg7+AvX20OgAA0L/W\n3o2zShMBAF15amwWBQBGdnfWlo3rShMBAF3ZnvZ046DKUABAXy6N5RQAYGStsvHK0kQAQFc+E9MN\nAGBkrbJxdmkiAKArp8R0AwAYWats/LQ0EQDQlSPTLhzemwIAbJpW2fhTaSIAoCs70y4c+1WGAgD6\n0iobu0sTAQBdeVTaheOQylAAQF/uytqy8c/SRABAVw5Oe7pxRGUoAKAvu7O2bOwpTQQAdOXQtKcb\nT6oMBQD05T9ZWzb+U5oIAOjK09OebhxeGQoA6EurbNxVmggA6Mr70i4cB1SGAgD60iob15QmAgC6\n8ou0CwcAwKZplY0vlyYCALpyd0w3AIARPSvtsvG6ylDAg9O26gDAaGZNMvzdA0u3vToAMIr3zDi/\nY6kpAICutZZSbixNBAB05XtpFw5LKQDApmmVjYtKEwEAXbk6vgYLAIxon7TLxgcqQwEAfbk5phsA\nwIgOSLtsnFoZCgDoy99jugEAjGhb2mXjxMpQAEBffhjTDQBgZK2y8ZbSRABAV06L6QYAMLJW2big\nNBFAg3crwLS1phn+roEtx+vpYbrOaZyznAIAbKrWcsobSxMBzGD0CtNlOQWYDEsqME2tScaepacA\nALp2XdYup7y/NBHAHMavME2WU4BJsaQCAIxO4QAARqdwAACjUzgAgNEpHADA6BQOAGB0Cgf044vV\nAQCAvpye9rtUflgZCgDoT6tw3HccVZgLAOjI2zO/dKwkObEsHQDQjc9muHSsJDm7KiAA0IddWax0\nrCS5PsmxNTEBgB7ckMWLx0pW3zj73JKkAMCkPTzJHVlf8VhJ8q8kn0/y5OVHBgCm6qFJfpX1F4/7\nH9cm+XSS5yw3OgAwRR/JAyseex83J7kgyduSHLnE6wAmbFt1AGBpnpjkS1neV2Vvzeq+kuvv/Xnj\nveduTXLLvT//muTPS8oDACzZtiQfTnJPNnf6sZnH1UnOS/Lm2FsCAN14d1b3bVQXjfUs7XwzyatH\n+F0AAEvylCQfy+rXZ6vLxaLHtVl9LgkAMHEnJ/l4kkuT7E59yZh1nDzWLwBYP5tGgbEckeRxSQ6/\n9+dhSQ5JcnCSg5IcmmRHkkePmOHyJEeP+O8DC1I4gK1ovyTHJ3l+khdk9XHs+27w37o5yc7NiQUA\nPNi8PMn5Se7K8PLKgUUZAYDOHJjkmrQLxzcKcwEAHXpC1haOG0sTAfZwAF1aaZzz/x0U2l4dAGCT\nHds4d9XSUwAAXftx1i6pfLo0EQDQndam0UeWJgIAuvLCtAsHAMCmaZWNH5QmAgC6clzahcO3UwCA\nTdMqGzeVJgIAuvKttAvHPpWhAIB+HJZ22fh9ZSjg/1nbBKZu1rdQ/P8GW4gnjQJTNmuPxgeXmgIA\n6NYv015KubsyFADQj/PSLhse8gUAbIrzM7tsPKUwFwDQiYszu2y8tjAXANCJyzO7bJxXmAsA6MQd\nmV02Li7MBQB0YlbRWEny9cJcAEAHnpj5ZePsumgAQA8+lvll46S6aABAD27I/LJxcF00AGDqHp75\nRWNPXTQAoAfvyvyycVVdNACgB3/M/LJxel00AGDqdmR+0VhJ8piydADA5H0h84vGbXXRAIAe7M78\nsvHxumgAwNS9KsNLKIeWpQMAJu+mzC8af6yLBgBM3dEZnmqcWpYOAJi832X4QV77lqUDACbtqAxP\nNb5Slg4AmLyhqcZKVp+/AQCwbs/McNH4WVk6AGDyrs1w2XhaVTgAYNpeluGi8ZuydADA5N0eUw0A\nYCQfzHDR+HVZOgBg0g7M6nMzhsrGE6oCAgDT9p0MF40Ly9IBAJP2jAwXjZUkj6wKCABM23UZLhqf\nKEsHAEzamRkuGncm2VYVEACYrkdkseWT11UFBACm7acZLhpXl6UDACbtuCw21Xh8VUAAYLq2ZbEn\nhZ5bFRAAmLbPZrho/D3J9qqAAMB07chiyycvrgoIAEzbZRkuGr8sSwcATNquLDbVOLgqIAAwbTdn\nuGh8qCwdADBp78hw0bilLB0AMGkPSfKPDJeNXVUBAYBp+0SGi8ZlZekAgEl7WJI9GS4bO6sCAgDT\ndk6Gi8aXytIBAJN2QJJ7Mr9o/Cur0w8AgHX7coanGmeUpQMAJu3RWez9JwAAG3JRhsvGm8rSAQCT\ntjPDReO2snQAwORdmuGycUpZOgBg8v6Q+UXjb3XRAIBezCsbby3MBQB0pFU07ixNBAB057H5/7Jx\nWm0cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAgIn5L5BG4zK/zThTAAAAAElFTkSuQmCC\n",
		"isbrushposition": 0,
		"disporder": 19
	}],
	"voList": {
		"is_leader": 1,
		"workticketid": workticketidx,
		"arrive_time": now
	}
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuitm35.append(caseinfo.copy())

#作业处理
workticketidx = workticketid + 3
caseinfo['id'] = 3406
caseinfo['name'] = '作业处理-用火作业-监护记录-收工记录'
#http://192.168.6.156/m/hse_m/HSE_CLOSE_RECORD_M/confirmCloseRecordAudit.json
url = 'http://192.168.6.156/m/hse_m/HSE_CLOSE_RECORD_M/confirmCloseRecordAudit.json'
data = {
	"mainAttributeVO": {},
	"auditPlainLineList": [{
		"actiontype": "sign",
		"isexmaineable": 1,
		"groupType": "4",
		"code": "2000000007688",
		"idnumber": "",
		"dataStatus": 0,
		"ismustaudit": 1,
		"force_photo": 0,
		"isEnd": 1,
		"ismulti": 0,
		"isShow": 1,
		"auditorder": 20,
		"isinputidnumber": 0,
		"electronicSignature": [{
			"imgStr": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAt6SURBVHic7d1dqKVVAQbgd2acHKdRhlEnLbVGLG3GyRTJUFHCi0xBogQh7Ae8qCz6\nIcnQi7Iu+oUQb8ouIivyoqRMQTBJ0SLsh9HCBswcp1HURsOfGU2dOV3sEdSz9tnfnLP3XvtbPQ8s\nzrAG9nnPvtj75VvrW18CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADNWVY7AEAPnJnktCQbk7xt31i/hNe7O8lt\nSX6b5NYlpwMAeuUDSe5MMldpfHPyfyIAMG0bktyXegVjofH+Cf7dAMAU3JH6haLr+OKE3gMAYIJq\nF4jFjpMn8WYAAJOxmC/7x5LckOTyDJY6TljC739zkk8kuWkROW5Ywu8FAKZo1Jf6tUnOrpDrcx2y\nzSXZWiEbALCfLsurv8DvyeA211nypyxcOrZVSwYANGdLhpeOmyvmAgAac0GGl47zK+YCABqzOcNL\nx4qKuQCAxpyVcuF4vmYoAKA9w26l/VjFTNCJh7cB9MtLKS+j+Dxnpi2vHQCA/XLwkPnvTzUFANC8\nH6W8tAIAMFalwvGNqokAgOZ8K65yAABTUCocK6smAgCasz2eKAsATNimWFahJ9y3DdBvpYLhs52Z\n4xwOgPbYx8HMUTgA+u32wtxF0w4BoygcAP32h8LcW6eeAkZQOAD6bWthTuFg5igcAP12X2HuuKmn\ngBEUDoB+e11h7oWpp4ARFA6AfltbmHtq6ilgBIUDoN8UDnpB4QDot5MLcw9PPQWMoHAA9NsZhbm7\npp4CAGja3sx/lsq6qomgwHn7AP3mWSr0giUVAGDiFA6A/tpUmNs79RQAQNNuzPz9G9dVTQQANOe1\nZWMuyVFVE8EQNhYB9JcNo/SGPRwA/fTVwtyeqacAAJpWWk75fNVEAEBTVqZcOAAAxub2zC8bz9UM\nBAC0p3R144KqiQCApnwqllMAgAkrlY3rqyYCAJrynri6AQBMWKls/LtqIgCgKZtSLhxraoYCANpS\nKhu7qyYCAJpyTsqF47CaoQCAtpTKxlNVEwEATfl4yoVjVc1QAEBbSmXjr1UTAQBNuSvO3QAAJmh1\nymXj6pqhYLGW1Q4AQNHelD+jfW7TS8trBwBgnqtSLhYnTTsIANCmFSkvpTxRMxQA0JYXY6MoADBB\n30u5bFxaMxQA0I7DUi4bz9YMBeNitzPAbBi2bOJzmia4SwWgvl1D5t871RQAQLN+k/JSytaaoQCA\ndlyUctlwVwoAMBaHZ3jZsNwNAIzFsLJxSs1QAEA7Xki5bHy3ZigAoB1/SblsbK8ZCgBox8WxSRQA\nmKA1GV42HO4FAIzFsLJxbM1QAEA7dqRcNr5dMxQA0I4rUy4bO2uGAgDa8YbYJAoATNiwsnFozVAA\nQDt2plw2rqgZCgBox1Upl41Ha4YCANpxaOzbAAAmbFjZWFszFADQjgdj3wYAMEEfjn0bAMAErYp9\nGwDAhA0rG0fXDAUAtOOWlMvGtTVDAQDtOCblsvFczVAwi5bVDgDQY8P2aPhshddYXjsAQE9dPWT+\n3KmmAACa5hZYAGCi/hy3wAIAE1YqG1+umggAaMqP4+oGADBhpbLxyaqJAICmHBdXNwCACftF5peN\nLVUTAQDNKV3dWF81EfSE0/AAuistn/gchQ6cNAoATJzCAbA0m2oHAADacn3cpQIATEGpcDxdNREA\n0JwnUy4dc0nurZgLAGjMsMLxynFhtXQAQBMOS7fSMZdkV5KL68QEAFqwM92Lx8vjb0k+nWRVhbxQ\njQNrAJbm/CQ3jeF17szgmPR7k9yT5I9jeE2YGQoHwHi8I4PScEil3/9ckt37fr5yPJ1kR5LtSR7Z\n9++Xx5NVkgIAY3FF9n+pZZbGHUmuSXJJkreP+b0BACbgMxlsHK1dIsYx9ib5YQZXcwCAGbUiyYeS\n3JL65WFc42tjfYdolj0cAPUdk+SsJCcm2bxvHF010eJsSLKtdghmk8IB0IY1SQ5Ksvo1P9clOSrJ\nG5O8JYMic3SSYyeU48EJvjYA0JATk1yewV03i11qAQBYlHOT3JxuheP5ShkBgMZcmoVLx1eqJQMA\nmnNqLK0AAFMw7IF2p9UMBQC056eZXzjur5qImeG2WADGZVkGp5GW5vk/t7x2AACaYc8GQykcAMDE\nKRwAjNMDhbkTp56CmaNwADBOWwpzp0w9BTNH4QBgnB4rzK2aegpmjsIBwDjtKcwdMPUUzByFA4Bx\nWlOY2z31FABA07Zm/uFfG6smYiY4jAWAcSqdxeG7BksqAMDkKRwAjIu7UQCAiftl5u/fuK1qIgCg\nOaXH06+vmggAaMpHUy4cAABjUyobv66aCABoytfj6gYAMEGHpFw2bq0ZitnjMBYAlmLYlQzfL7yK\nczgAWKwnh8yfN9UUAECzbk95KeXhipkAgIZ8KeWyYaMoADAWC5WN11fMBQA0YqGycWrFXABAI36S\n4WXjsoq5AIBG/D7Dy8Y1FXMBAI34V4aXjesq5gIAGjGsaMwl+VnFXABAA4YdV/7yuLJeNACgBadn\n4bLxvnrRAIAW/CoLl40T6kUDAFqwOwuXjQPqRQMA+u5NWbhoPFMvGgDQgu9k4bJxd71oAEALRi2h\nXFgvGgDQd+dm4aLhIWwAwJL8PQsXjYfrRQMA+u6kjL6qcUW1dABA723J6LKxulo6AKDXjs/oovG7\naukAgN57IKPLxruqpQMAeu2SjC4aD1ZLBwD02oFJ/pvRZeOMWgEBgH77eUYXje3V0gEAvfaRjC4a\nc0neWSsgANBfRybZm9FF46ZaAQGA/lqWZFtGF409SQ6uExEA6LMb02355LO1AgIA/XVluhWNu2oF\nBAD66+x0Kxq7k6yqlBEA6KmN6VY0nKkBAOy3DRls9uxSNL5QKSMA0FNHptsJoXNJflApIwDQU+uS\n7IoNoQDABKxJ8p90Kxr3J1leJyYA0EcHJnk03YrGjiQr68QEAPpoZZKH0q1o7Eyyuk5MAKCPViV5\nJN2KxjNJ1taJCQD00UFJHk+3ovF8kvV1YgIAfXRwkifSrWi8lOSYOjEBgD5am+SpdCsae5McXycm\nANBH65I8m+5FY2OdmABAHx2R7s86mYuiAQDshw1JXki3krEnyXF1YgIAfbQ5gyWRrptBFQ0AoLNT\n033Z5KUMroAAAHRyTroXjRejaAAA++G8dC8az8c5GgDAfrgg3YvG00kOrxMTAOijD6Z70diZwUmi\nAACdnJbuReORDB7CBgDQyUXpXjR2VMoIAPTUmeleNP6RZEWdmABAH21O96KxLckBVVICAL31z3Qr\nGg/VCggA9Nu7020zKDBlLiMCLTl9gf/blcHTXp+dUhYAoGGlqxpHVE0EADTp8QyKhqe3AgAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwCv8D51l3ZYxYqwmAAAAAElFTkSu\nQmCC\n",
			"uuid": ""
		}],
		"name": "监护人确认",
		"audittype": "sign,card",
		"specialworktype": "",
		"value": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAt6SURBVHic7d1dqKVVAQbgd2acHKdRhlEnLbVGLG3GyRTJUFHCi0xBogQh7Ae8qCz6\nIcnQi7Iu+oUQb8ouIivyoqRMQTBJ0SLsh9HCBswcp1HURsOfGU2dOV3sEdSz9tnfnLP3XvtbPQ8s\nzrAG9nnPvtj75VvrW18CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADNWVY7AEAPnJnktCQbk7xt31i/hNe7O8lt\nSX6b5NYlpwMAeuUDSe5MMldpfHPyfyIAMG0bktyXegVjofH+Cf7dAMAU3JH6haLr+OKE3gMAYIJq\nF4jFjpMn8WYAAJOxmC/7x5LckOTyDJY6TljC739zkk8kuWkROW5Ywu8FAKZo1Jf6tUnOrpDrcx2y\nzSXZWiEbALCfLsurv8DvyeA211nypyxcOrZVSwYANGdLhpeOmyvmAgAac0GGl47zK+YCABqzOcNL\nx4qKuQCAxpyVcuF4vmYoAKA9w26l/VjFTNCJh7cB9MtLKS+j+Dxnpi2vHQCA/XLwkPnvTzUFANC8\nH6W8tAIAMFalwvGNqokAgOZ8K65yAABTUCocK6smAgCasz2eKAsATNimWFahJ9y3DdBvpYLhs52Z\n4xwOgPbYx8HMUTgA+u32wtxF0w4BoygcAP32h8LcW6eeAkZQOAD6bWthTuFg5igcAP12X2HuuKmn\ngBEUDoB+e11h7oWpp4ARFA6AfltbmHtq6ilgBIUDoN8UDnpB4QDot5MLcw9PPQWMoHAA9NsZhbm7\npp4CAGja3sx/lsq6qomgwHn7AP3mWSr0giUVAGDiFA6A/tpUmNs79RQAQNNuzPz9G9dVTQQANOe1\nZWMuyVFVE8EQNhYB9JcNo/SGPRwA/fTVwtyeqacAAJpWWk75fNVEAEBTVqZcOAAAxub2zC8bz9UM\nBAC0p3R144KqiQCApnwqllMAgAkrlY3rqyYCAJrynri6AQBMWKls/LtqIgCgKZtSLhxraoYCANpS\nKhu7qyYCAJpyTsqF47CaoQCAtpTKxlNVEwEATfl4yoVjVc1QAEBbSmXjr1UTAQBNuSvO3QAAJmh1\nymXj6pqhYLGW1Q4AQNHelD+jfW7TS8trBwBgnqtSLhYnTTsIANCmFSkvpTxRMxQA0JYXY6MoADBB\n30u5bFxaMxQA0I7DUi4bz9YMBeNitzPAbBi2bOJzmia4SwWgvl1D5t871RQAQLN+k/JSytaaoQCA\ndlyUctlwVwoAMBaHZ3jZsNwNAIzFsLJxSs1QAEA7Xki5bHy3ZigAoB1/SblsbK8ZCgBox8WxSRQA\nmKA1GV42HO4FAIzFsLJxbM1QAEA7dqRcNr5dMxQA0I4rUy4bO2uGAgDa8YbYJAoATNiwsnFozVAA\nQDt2plw2rqgZCgBox1Upl41Ha4YCANpxaOzbAAAmbFjZWFszFADQjgdj3wYAMEEfjn0bAMAErYp9\nGwDAhA0rG0fXDAUAtOOWlMvGtTVDAQDtOCblsvFczVAwi5bVDgDQY8P2aPhshddYXjsAQE9dPWT+\n3KmmAACa5hZYAGCi/hy3wAIAE1YqG1+umggAaMqP4+oGADBhpbLxyaqJAICmHBdXNwCACftF5peN\nLVUTAQDNKV3dWF81EfSE0/AAuistn/gchQ6cNAoATJzCAbA0m2oHAADacn3cpQIATEGpcDxdNREA\n0JwnUy4dc0nurZgLAGjMsMLxynFhtXQAQBMOS7fSMZdkV5KL68QEAFqwM92Lx8vjb0k+nWRVhbxQ\njQNrAJbm/CQ3jeF17szgmPR7k9yT5I9jeE2YGQoHwHi8I4PScEil3/9ckt37fr5yPJ1kR5LtSR7Z\n9++Xx5NVkgIAY3FF9n+pZZbGHUmuSXJJkreP+b0BACbgMxlsHK1dIsYx9ib5YQZXcwCAGbUiyYeS\n3JL65WFc42tjfYdolj0cAPUdk+SsJCcm2bxvHF010eJsSLKtdghmk8IB0IY1SQ5Ksvo1P9clOSrJ\nG5O8JYMic3SSYyeU48EJvjYA0JATk1yewV03i11qAQBYlHOT3JxuheP5ShkBgMZcmoVLx1eqJQMA\nmnNqLK0AAFMw7IF2p9UMBQC056eZXzjur5qImeG2WADGZVkGp5GW5vk/t7x2AACaYc8GQykcAMDE\nKRwAjNMDhbkTp56CmaNwADBOWwpzp0w9BTNH4QBgnB4rzK2aegpmjsIBwDjtKcwdMPUUzByFA4Bx\nWlOY2z31FABA07Zm/uFfG6smYiY4jAWAcSqdxeG7BksqAMDkKRwAjIu7UQCAiftl5u/fuK1qIgCg\nOaXH06+vmggAaMpHUy4cAABjUyobv66aCABoytfj6gYAMEGHpFw2bq0ZitnjMBYAlmLYlQzfL7yK\nczgAWKwnh8yfN9UUAECzbk95KeXhipkAgIZ8KeWyYaMoADAWC5WN11fMBQA0YqGycWrFXABAI36S\n4WXjsoq5AIBG/D7Dy8Y1FXMBAI34V4aXjesq5gIAGjGsaMwl+VnFXABAA4YdV/7yuLJeNACgBadn\n4bLxvnrRAIAW/CoLl40T6kUDAFqwOwuXjQPqRQMA+u5NWbhoPFMvGgDQgu9k4bJxd71oAEALRi2h\nXFgvGgDQd+dm4aLhIWwAwJL8PQsXjYfrRQMA+u6kjL6qcUW1dABA723J6LKxulo6AKDXjs/oovG7\naukAgN57IKPLxruqpQMAeu2SjC4aD1ZLBwD02oFJ/pvRZeOMWgEBgH77eUYXje3V0gEAvfaRjC4a\nc0neWSsgANBfRybZm9FF46ZaAQGA/lqWZFtGF409SQ6uExEA6LMb02355LO1AgIA/XVluhWNu2oF\nBAD66+x0Kxq7k6yqlBEA6KmN6VY0nKkBAOy3DRls9uxSNL5QKSMA0FNHptsJoXNJflApIwDQU+uS\n7IoNoQDABKxJ8p90Kxr3J1leJyYA0EcHJnk03YrGjiQr68QEAPpoZZKH0q1o7Eyyuk5MAKCPViV5\nJN2KxjNJ1taJCQD00UFJHk+3ovF8kvV1YgIAfXRwkifSrWi8lOSYOjEBgD5am+SpdCsae5McXycm\nANBH65I8m+5FY2OdmABAHx2R7s86mYuiAQDshw1JXki3krEnyXF1YgIAfbQ5gyWRrptBFQ0AoLNT\n033Z5KUMroAAAHRyTroXjRejaAAA++G8dC8az8c5GgDAfrgg3YvG00kOrxMTAOijD6Z70diZwUmi\nAACdnJbuReORDB7CBgDQyUXpXjR2VMoIAPTUmeleNP6RZEWdmABAH21O96KxLckBVVICAL31z3Qr\nGg/VCggA9Nu7020zKDBlLiMCLTl9gf/blcHTXp+dUhYAoGGlqxpHVE0EADTp8QyKhqe3AgAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwCv8D51l3ZYxYqwmAAAAAElFTkSu\nQmCC\n",
		"isbrushposition": 0,
		"disporder": 20
	}],
	"voList": {
		"leave_status": 1,
		"workType": "dh",
		"clear_status": 1,
		"workticketid": workticketidx
	}
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuitm35.append(caseinfo.copy())

#作业处理
workticketidx = workticketid + 3
caseinfo['id'] = 3407
caseinfo['name'] = '作业处理-用火作业-暂停'
#http://192.168.6.156/m/hse_m/HSE_WORKTASK_INJOB_M/pauseSaveAudit.json?reason=%E5%93%88%E5%93%88&workticketid=2000000003772
#url = 'http://192.168.6.156/m/hse_m/HSE_WORKTASK_INJOB_M/pauseSaveAudit.json?reason=%E5%93%88%E5%93%88&workticketid=%d'%(workticketidx)
url = 'http://192.168.6.156/m/hse_m/HSE_WORKTASK_INJOB_M/pauseSaveAudit.json?reason=%E5%93%88%E5%93%88&workticketid='+str(workticketidx)
data = {
	"mainAttributeVO": {},
	"auditPlainLineList": [{
		"actiontype": "sign",
		"isexmaineable": 1,
		"groupType": "4",
		"code": "2000000007927",
		"idnumber": "",
		"dataStatus": 0,
		"ismustaudit": 1,
		"force_photo": 0,
		"isEnd": 1,
		"ismulti": 0,
		"isShow": 1,
		"auditorder": 1,
		"isinputidnumber": 0,
		"electronicSignature": [{
			"imgStr": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAkaSURBVHic7d1NqKZlGQfwyzPMkDSBELiQQDCYNoL2NWMJiquSdkOggq0a+yAJqRZF\nuBEJ2wSCCzUioiiGigYrF60qWqRIO2kRKkJJJrZIjbL5cOHKue+3857zPvdzvc/1/n5wNvfqvzpc\nXP/7ud8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2E7nIuKvEXFDdhAA\noKZLl/2dyo0DAFRzPNqB4+XURFDYXnYAgCRf75w9P3sKAKC0/0W74fhUaiIo7IrsAABJLnXO/E+E\nQVQqwC46nh0AAKjvkWjrlN+nJgIAyrl82LgUESdTE0Fx+kpgF7m/ATNzhwPYNV/onF2YPQUAUNp/\no61TvpiaCHaAFSKwa9QpkEClAuwSD3sBAMO9Gm2d8u3URLAjrBGBXaJOgSQqFWBXfDQ7AABQ3wvR\n1infT00EAJTTe130WGoiAKCUj0R/4AAAmMyL0Q4bP0xNBACUo04BAIb6cKhTAIDBenXKj1MTAQDl\nqFMAgKHUKQDAcL065WxqIgCgnN5248rURABAKR8KdQoAMFivTvlZaiIAoBx1CgAw1AdDnQIADNar\nU36RmggAKKe33XhPaiIAoJQbQ50CAAzWq1OeSE0EAJSjTgEAhlKnAADD/SXaYePXqYkAgHLUKQDA\nUB8PdQoAMNjfox02zqUmAgDK8dspAMBQt4c6BQAY7F/RDhs/SE0EAJTT224cSU0EvMNedgCADX1m\nxfmFWVMAAKWdj3a78XBqIqBxRXYAgA31Lof63wZbRqUCLNkD2QEAgPp6l0XvTU0EAJRyJLy9AYuh\nUgGW6keds//MngIAKK233fhEaiIAoJRrQp0CAAz2fLTDxnOpiQCAcnrbjWtSEwEApXw61CkAwGAX\nwi/DwuJ4/hdYmt42Y2/FObAlvMMBLMl3VpwbNgCAyfTubnw+NREAUMpV4bIoADDYM9EOG/9ITQQA\nlNPbbpxITQQAlHI61CkAwGDe3oCF8w4HsAS9bYb/X7Ag3uEAtt13O2cXZ08BAJTWu7txOjURAFDK\nteGyKAAw2EvRDht/TE0EAJTT2268OzURAFDKmVCnAACD9YaN+1MTAYfmO3ZgG+3F2499Xc7/LFgo\n73AA2+gnnbM3Zk8BAJTWq1M+lpoIACjlRLgsCgAM9kq0w8aTqYkAgHJ6242jqYkAgFLuC3UKADBY\nb9j4SmoiAKCUo2G7AQAM9qtoh41XUhMBAOX0thsnUhMBAKWcCnUKADDY69EOGz9NTQRMyg8hAdug\nt804EhEX5w4CjOHH24Bs31xxbtgAACbTu7vxudREAEAp7wqXRQGAwZ6Idth4KTURAFBOb7txXWoi\nAKCU94U6BQAY7Nloh43fpCYCAMrpbTeOpyYCAEq5LdQpAMBgr0U7bDyemggYytPmQIbeNmNvxTlQ\ngKfNgbmdWXFu2AAAJnMx2jrlG6mJgOFUKsDcepsM/4ugOJUKMKdvdc4uzJ4CACit9ynsXamJAIBS\njoa3NwCAwc5GO2z8MzURAFBOb7txU2oiAKCUq0OdAgAM9ky0w8afUhMBAOX0thtXpyYCAEo5GeoU\nAGCwl6MdNn6emggAKKe33TiamggAKOWToU4BAAZ7Ldph47HUREAKv9AIjNTbZuytOAcK82uxwCh3\nrjg3bAAAk3kz2jrlodREQBqVCjBKb5Phfw7sKJUKMMKZ7AAAQH3no61T7k9NBKSy3gRGUKcA76BS\nAab2pewAAEB9F6OtU76amghIZ8UJTE2dAjRUKsCUvtw589AXADCpXp1yb2oiYCtYcwJTUqcAXSoV\nYCrqFABgOHUKsJJVJzAVdQqwkkoFmMI92QEAgPp6v53ytdREwFax7gSmoE4B/i+VCrCpO7MDAAD1\n/TvaOuXB1ETA1rHyBDalTgH2pVIBNnFzdgAAoL4Xoq1TvpeaCAAo5/Jh41JEHEtNBACU8t7oDxwA\nAJN5NNph46nURABAOb3txi2piYCt5dM14LB8DguszWexwGFcnx0AAKjvl9HWKWdTEwEA5fTub1yX\nmgjYavpW4DDc3wAOxB0OAGA4AwdwUHd3zv48ewoAoLQ/RHt/477URABAOb0Lo1emJgK2nktewEG5\nMAocmDscAMBwBg7gID7QOXtz9hTA4hg4gIM43Tk7N3sKAKC0p6O9MHpHaiIAoJzeFyrHUhMBi+Bm\nOXAQvlABDsUdDgBgOAMHADCcgQNY142dsxdnTwEskoEDWNetnbPfzZ4CWCQDB7AuAwcAMNyr0X4S\n+/7URMBi+JwNWJdPYoFDU6kAAMMZOACA4QwcAMBwBg5gHVd1zs7PngJYLAMHsI5TnbOnZk8BLJaB\nA1iHgQPYiIEDWMdNnTMDBwAwqd6jX9emJgIWxaM9wDo8+gVsRKUCAAxn4AAAhjNwAADDGTiA/bir\nAWzMwAHs52Tn7NnZUwCLZuAA9uMNDmBjBg5gP14ZBQCGey7aR79uSE0EAJTzt2gHDgCASd0eBg4A\nYAafjbcHjd8m5wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANhS\nbwFPYJbTu2QQ6gAAAABJRU5ErkJggg==\n",
			"uuid": ""
		}],
		"name": "申请人",
		"audittype": "sign,card",
		"specialworktype": "",
		"value": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAkaSURBVHic7d1NqKZlGQfwyzPMkDSBELiQQDCYNoL2NWMJiquSdkOggq0a+yAJqRZF\nuBEJ2wSCCzUioiiGigYrF60qWqRIO2kRKkJJJrZIjbL5cOHKue+3857zPvdzvc/1/n5wNvfqvzpc\nXP/7ud8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2E7nIuKvEXFDdhAA\noKZLl/2dyo0DAFRzPNqB4+XURFDYXnYAgCRf75w9P3sKAKC0/0W74fhUaiIo7IrsAABJLnXO/E+E\nQVQqwC46nh0AAKjvkWjrlN+nJgIAyrl82LgUESdTE0Fx+kpgF7m/ATNzhwPYNV/onF2YPQUAUNp/\no61TvpiaCHaAFSKwa9QpkEClAuwSD3sBAMO9Gm2d8u3URLAjrBGBXaJOgSQqFWBXfDQ7AABQ3wvR\n1infT00EAJTTe130WGoiAKCUj0R/4AAAmMyL0Q4bP0xNBACUo04BAIb6cKhTAIDBenXKj1MTAQDl\nqFMAgKHUKQDAcL065WxqIgCgnN5248rURABAKR8KdQoAMFivTvlZaiIAoBx1CgAw1AdDnQIADNar\nU36RmggAKKe33XhPaiIAoJQbQ50CAAzWq1OeSE0EAJSjTgEAhlKnAADD/SXaYePXqYkAgHLUKQDA\nUB8PdQoAMNjfox02zqUmAgDK8dspAMBQt4c6BQAY7F/RDhs/SE0EAJTT224cSU0EvMNedgCADX1m\nxfmFWVMAAKWdj3a78XBqIqBxRXYAgA31Lof63wZbRqUCLNkD2QEAgPp6l0XvTU0EAJRyJLy9AYuh\nUgGW6keds//MngIAKK233fhEaiIAoJRrQp0CAAz2fLTDxnOpiQCAcnrbjWtSEwEApXw61CkAwGAX\nwi/DwuJ4/hdYmt42Y2/FObAlvMMBLMl3VpwbNgCAyfTubnw+NREAUMpV4bIoADDYM9EOG/9ITQQA\nlNPbbpxITQQAlHI61CkAwGDe3oCF8w4HsAS9bYb/X7Ag3uEAtt13O2cXZ08BAJTWu7txOjURAFDK\nteGyKAAw2EvRDht/TE0EAJTT2268OzURAFDKmVCnAACD9YaN+1MTAYfmO3ZgG+3F2499Xc7/LFgo\n73AA2+gnnbM3Zk8BAJTWq1M+lpoIACjlRLgsCgAM9kq0w8aTqYkAgHJ6242jqYkAgFLuC3UKADBY\nb9j4SmoiAKCUo2G7AQAM9qtoh41XUhMBAOX0thsnUhMBAKWcCnUKADDY69EOGz9NTQRMyg8hAdug\nt804EhEX5w4CjOHH24Bs31xxbtgAACbTu7vxudREAEAp7wqXRQGAwZ6Idth4KTURAFBOb7txXWoi\nAKCU94U6BQAY7Nloh43fpCYCAMrpbTeOpyYCAEq5LdQpAMBgr0U7bDyemggYytPmQIbeNmNvxTlQ\ngKfNgbmdWXFu2AAAJnMx2jrlG6mJgOFUKsDcepsM/4ugOJUKMKdvdc4uzJ4CACit9ynsXamJAIBS\njoa3NwCAwc5GO2z8MzURAFBOb7txU2oiAKCUq0OdAgAM9ky0w8afUhMBAOX0thtXpyYCAEo5GeoU\nAGCwl6MdNn6emggAKKe33TiamggAKOWToU4BAAZ7Ldph47HUREAKv9AIjNTbZuytOAcK82uxwCh3\nrjg3bAAAk3kz2jrlodREQBqVCjBKb5Phfw7sKJUKMMKZ7AAAQH3no61T7k9NBKSy3gRGUKcA76BS\nAab2pewAAEB9F6OtU76amghIZ8UJTE2dAjRUKsCUvtw589AXADCpXp1yb2oiYCtYcwJTUqcAXSoV\nYCrqFABgOHUKsJJVJzAVdQqwkkoFmMI92QEAgPp6v53ytdREwFax7gSmoE4B/i+VCrCpO7MDAAD1\n/TvaOuXB1ETA1rHyBDalTgH2pVIBNnFzdgAAoL4Xoq1TvpeaCAAo5/Jh41JEHEtNBACU8t7oDxwA\nAJN5NNph46nURABAOb3txi2piYCt5dM14LB8DguszWexwGFcnx0AAKjvl9HWKWdTEwEA5fTub1yX\nmgjYavpW4DDc3wAOxB0OAGA4AwdwUHd3zv48ewoAoLQ/RHt/477URABAOb0Lo1emJgK2nktewEG5\nMAocmDscAMBwBg7gID7QOXtz9hTA4hg4gIM43Tk7N3sKAKC0p6O9MHpHaiIAoJzeFyrHUhMBi+Bm\nOXAQvlABDsUdDgBgOAMHADCcgQNY142dsxdnTwEskoEDWNetnbPfzZ4CWCQDB7AuAwcAMNyr0X4S\n+/7URMBi+JwNWJdPYoFDU6kAAMMZOACA4QwcAMBwBg5gHVd1zs7PngJYLAMHsI5TnbOnZk8BLJaB\nA1iHgQPYiIEDWMdNnTMDBwAwqd6jX9emJgIWxaM9wDo8+gVsRKUCAAxn4AAAhjNwAADDGTiA/bir\nAWzMwAHs52Tn7NnZUwCLZuAA9uMNDmBjBg5gP14ZBQCGey7aR79uSE0EAJTzt2gHDgCASd0eBg4A\nYAafjbcHjd8m5wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANhS\nbwFPYJbTu2QQ6gAAAABJRU5ErkJggg==\n",
		"isbrushposition": 0,
		"disporder": 1
	}],
	"voList": {
		"auditPlainLineList": [{
			"actiontype": "sign",
			"isexmaineable": 1,
			"groupType": "4",
			"code": "2000000007927",
			"idnumber": "",
			"dataStatus": 0,
			"ismustaudit": 1,
			"force_photo": 0,
			"isEnd": 1,
			"ismulti": 0,
			"isShow": 1,
			"auditorder": 1,
			"isinputidnumber": 0,
			"electronicSignature": [{
				"imgStr": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAkaSURBVHic7d1NqKZlGQfwyzPMkDSBELiQQDCYNoL2NWMJiquSdkOggq0a+yAJqRZF\nuBEJ2wSCCzUioiiGigYrF60qWqRIO2kRKkJJJrZIjbL5cOHKue+3857zPvdzvc/1/n5wNvfqvzpc\nXP/7ud8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2E7nIuKvEXFDdhAA\noKZLl/2dyo0DAFRzPNqB4+XURFDYXnYAgCRf75w9P3sKAKC0/0W74fhUaiIo7IrsAABJLnXO/E+E\nQVQqwC46nh0AAKjvkWjrlN+nJgIAyrl82LgUESdTE0Fx+kpgF7m/ATNzhwPYNV/onF2YPQUAUNp/\no61TvpiaCHaAFSKwa9QpkEClAuwSD3sBAMO9Gm2d8u3URLAjrBGBXaJOgSQqFWBXfDQ7AABQ3wvR\n1infT00EAJTTe130WGoiAKCUj0R/4AAAmMyL0Q4bP0xNBACUo04BAIb6cKhTAIDBenXKj1MTAQDl\nqFMAgKHUKQDAcL065WxqIgCgnN5248rURABAKR8KdQoAMFivTvlZaiIAoBx1CgAw1AdDnQIADNar\nU36RmggAKKe33XhPaiIAoJQbQ50CAAzWq1OeSE0EAJSjTgEAhlKnAADD/SXaYePXqYkAgHLUKQDA\nUB8PdQoAMNjfox02zqUmAgDK8dspAMBQt4c6BQAY7F/RDhs/SE0EAJTT224cSU0EvMNedgCADX1m\nxfmFWVMAAKWdj3a78XBqIqBxRXYAgA31Lof63wZbRqUCLNkD2QEAgPp6l0XvTU0EAJRyJLy9AYuh\nUgGW6keds//MngIAKK233fhEaiIAoJRrQp0CAAz2fLTDxnOpiQCAcnrbjWtSEwEApXw61CkAwGAX\nwi/DwuJ4/hdYmt42Y2/FObAlvMMBLMl3VpwbNgCAyfTubnw+NREAUMpV4bIoADDYM9EOG/9ITQQA\nlNPbbpxITQQAlHI61CkAwGDe3oCF8w4HsAS9bYb/X7Ag3uEAtt13O2cXZ08BAJTWu7txOjURAFDK\nteGyKAAw2EvRDht/TE0EAJTT2268OzURAFDKmVCnAACD9YaN+1MTAYfmO3ZgG+3F2499Xc7/LFgo\n73AA2+gnnbM3Zk8BAJTWq1M+lpoIACjlRLgsCgAM9kq0w8aTqYkAgHJ6242jqYkAgFLuC3UKADBY\nb9j4SmoiAKCUo2G7AQAM9qtoh41XUhMBAOX0thsnUhMBAKWcCnUKADDY69EOGz9NTQRMyg8hAdug\nt804EhEX5w4CjOHH24Bs31xxbtgAACbTu7vxudREAEAp7wqXRQGAwZ6Idth4KTURAFBOb7txXWoi\nAKCU94U6BQAY7Nloh43fpCYCAMrpbTeOpyYCAEq5LdQpAMBgr0U7bDyemggYytPmQIbeNmNvxTlQ\ngKfNgbmdWXFu2AAAJnMx2jrlG6mJgOFUKsDcepsM/4ugOJUKMKdvdc4uzJ4CACit9ynsXamJAIBS\njoa3NwCAwc5GO2z8MzURAFBOb7txU2oiAKCUq0OdAgAM9ky0w8afUhMBAOX0thtXpyYCAEo5GeoU\nAGCwl6MdNn6emggAKKe33TiamggAKOWToU4BAAZ7Ldph47HUREAKv9AIjNTbZuytOAcK82uxwCh3\nrjg3bAAAk3kz2jrlodREQBqVCjBKb5Phfw7sKJUKMMKZ7AAAQH3no61T7k9NBKSy3gRGUKcA76BS\nAab2pewAAEB9F6OtU76amghIZ8UJTE2dAjRUKsCUvtw589AXADCpXp1yb2oiYCtYcwJTUqcAXSoV\nYCrqFABgOHUKsJJVJzAVdQqwkkoFmMI92QEAgPp6v53ytdREwFax7gSmoE4B/i+VCrCpO7MDAAD1\n/TvaOuXB1ETA1rHyBDalTgH2pVIBNnFzdgAAoL4Xoq1TvpeaCAAo5/Jh41JEHEtNBACU8t7oDxwA\nAJN5NNph46nURABAOb3txi2piYCt5dM14LB8DguszWexwGFcnx0AAKjvl9HWKWdTEwEA5fTub1yX\nmgjYavpW4DDc3wAOxB0OAGA4AwdwUHd3zv48ewoAoLQ/RHt/477URABAOb0Lo1emJgK2nktewEG5\nMAocmDscAMBwBg7gID7QOXtz9hTA4hg4gIM43Tk7N3sKAKC0p6O9MHpHaiIAoJzeFyrHUhMBi+Bm\nOXAQvlABDsUdDgBgOAMHADCcgQNY142dsxdnTwEskoEDWNetnbPfzZ4CWCQDB7AuAwcAMNyr0X4S\n+/7URMBi+JwNWJdPYoFDU6kAAMMZOACA4QwcAMBwBg5gHVd1zs7PngJYLAMHsI5TnbOnZk8BLJaB\nA1iHgQPYiIEDWMdNnTMDBwAwqd6jX9emJgIWxaM9wDo8+gVsRKUCAAxn4AAAhjNwAADDGTiA/bir\nAWzMwAHs52Tn7NnZUwCLZuAA9uMNDmBjBg5gP14ZBQCGey7aR79uSE0EAJTzt2gHDgCASd0eBg4A\nYAafjbcHjd8m5wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANhS\nbwFPYJbTu2QQ6gAAAABJRU5ErkJggg==\n",
				"uuid": ""
			}],
			"name": "申请人",
			"audittype": "sign,card",
			"specialworktype": "",
			"value": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAkaSURBVHic7d1NqKZlGQfwyzPMkDSBELiQQDCYNoL2NWMJiquSdkOggq0a+yAJqRZF\nuBEJ2wSCCzUioiiGigYrF60qWqRIO2kRKkJJJrZIjbL5cOHKue+3857zPvdzvc/1/n5wNvfqvzpc\nXP/7ud8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2E7nIuKvEXFDdhAA\noKZLl/2dyo0DAFRzPNqB4+XURFDYXnYAgCRf75w9P3sKAKC0/0W74fhUaiIo7IrsAABJLnXO/E+E\nQVQqwC46nh0AAKjvkWjrlN+nJgIAyrl82LgUESdTE0Fx+kpgF7m/ATNzhwPYNV/onF2YPQUAUNp/\no61TvpiaCHaAFSKwa9QpkEClAuwSD3sBAMO9Gm2d8u3URLAjrBGBXaJOgSQqFWBXfDQ7AABQ3wvR\n1infT00EAJTTe130WGoiAKCUj0R/4AAAmMyL0Q4bP0xNBACUo04BAIb6cKhTAIDBenXKj1MTAQDl\nqFMAgKHUKQDAcL065WxqIgCgnN5248rURABAKR8KdQoAMFivTvlZaiIAoBx1CgAw1AdDnQIADNar\nU36RmggAKKe33XhPaiIAoJQbQ50CAAzWq1OeSE0EAJSjTgEAhlKnAADD/SXaYePXqYkAgHLUKQDA\nUB8PdQoAMNjfox02zqUmAgDK8dspAMBQt4c6BQAY7F/RDhs/SE0EAJTT224cSU0EvMNedgCADX1m\nxfmFWVMAAKWdj3a78XBqIqBxRXYAgA31Lof63wZbRqUCLNkD2QEAgPp6l0XvTU0EAJRyJLy9AYuh\nUgGW6keds//MngIAKK233fhEaiIAoJRrQp0CAAz2fLTDxnOpiQCAcnrbjWtSEwEApXw61CkAwGAX\nwi/DwuJ4/hdYmt42Y2/FObAlvMMBLMl3VpwbNgCAyfTubnw+NREAUMpV4bIoADDYM9EOG/9ITQQA\nlNPbbpxITQQAlHI61CkAwGDe3oCF8w4HsAS9bYb/X7Ag3uEAtt13O2cXZ08BAJTWu7txOjURAFDK\nteGyKAAw2EvRDht/TE0EAJTT2268OzURAFDKmVCnAACD9YaN+1MTAYfmO3ZgG+3F2499Xc7/LFgo\n73AA2+gnnbM3Zk8BAJTWq1M+lpoIACjlRLgsCgAM9kq0w8aTqYkAgHJ6242jqYkAgFLuC3UKADBY\nb9j4SmoiAKCUo2G7AQAM9qtoh41XUhMBAOX0thsnUhMBAKWcCnUKADDY69EOGz9NTQRMyg8hAdug\nt804EhEX5w4CjOHH24Bs31xxbtgAACbTu7vxudREAEAp7wqXRQGAwZ6Idth4KTURAFBOb7txXWoi\nAKCU94U6BQAY7Nloh43fpCYCAMrpbTeOpyYCAEq5LdQpAMBgr0U7bDyemggYytPmQIbeNmNvxTlQ\ngKfNgbmdWXFu2AAAJnMx2jrlG6mJgOFUKsDcepsM/4ugOJUKMKdvdc4uzJ4CACit9ynsXamJAIBS\njoa3NwCAwc5GO2z8MzURAFBOb7txU2oiAKCUq0OdAgAM9ky0w8afUhMBAOX0thtXpyYCAEo5GeoU\nAGCwl6MdNn6emggAKKe33TiamggAKOWToU4BAAZ7Ldph47HUREAKv9AIjNTbZuytOAcK82uxwCh3\nrjg3bAAAk3kz2jrlodREQBqVCjBKb5Phfw7sKJUKMMKZ7AAAQH3no61T7k9NBKSy3gRGUKcA76BS\nAab2pewAAEB9F6OtU76amghIZ8UJTE2dAjRUKsCUvtw589AXADCpXp1yb2oiYCtYcwJTUqcAXSoV\nYCrqFABgOHUKsJJVJzAVdQqwkkoFmMI92QEAgPp6v53ytdREwFax7gSmoE4B/i+VCrCpO7MDAAD1\n/TvaOuXB1ETA1rHyBDalTgH2pVIBNnFzdgAAoL4Xoq1TvpeaCAAo5/Jh41JEHEtNBACU8t7oDxwA\nAJN5NNph46nURABAOb3txi2piYCt5dM14LB8DguszWexwGFcnx0AAKjvl9HWKWdTEwEA5fTub1yX\nmgjYavpW4DDc3wAOxB0OAGA4AwdwUHd3zv48ewoAoLQ/RHt/477URABAOb0Lo1emJgK2nktewEG5\nMAocmDscAMBwBg7gID7QOXtz9hTA4hg4gIM43Tk7N3sKAKC0p6O9MHpHaiIAoJzeFyrHUhMBi+Bm\nOXAQvlABDsUdDgBgOAMHADCcgQNY142dsxdnTwEskoEDWNetnbPfzZ4CWCQDB7AuAwcAMNyr0X4S\n+/7URMBi+JwNWJdPYoFDU6kAAMMZOACA4QwcAMBwBg5gHVd1zs7PngJYLAMHsI5TnbOnZk8BLJaB\nA1iHgQPYiIEDWMdNnTMDBwAwqd6jX9emJgIWxaM9wDo8+gVsRKUCAAxn4AAAhjNwAADDGTiA/bir\nAWzMwAHs52Tn7NnZUwCLZuAA9uMNDmBjBg5gP14ZBQCGey7aR79uSE0EAJTzt2gHDgCASd0eBg4A\nYAafjbcHjd8m5wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANhS\nbwFPYJbTu2QQ6gAAAABJRU5ErkJggg==\n",
			"isbrushposition": 0,
			"disporder": 1
		}]
	}
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuitm35.append(caseinfo.copy())

#作业处理
workticketidx = workticketid + 3
caseinfo['id'] = 3407
caseinfo['name'] = '作业处理-用火作业-恢复-确认人签字'
#http://192.168.6.156/m/hse_m/HSE_WORKTASK_INJOB_M/recoverSaveAudit.json?workticketid=2000000003772&workType=dh&worklevel=gb_dh_workLevel01&datatype=gas&businesstype=&detectiontype=retest
url = 'http://192.168.6.156/m/hse_m/HSE_WORKTASK_INJOB_M/recoverSaveAudit.json?workticketid=%d&workType=dh&worklevel=gb_dh_workLevel01&datatype=gas&businesstype=&detectiontype=retest'%(workticketidx)
data = {
	"mainAttributeVO": {},
	"auditPlainLineList": [{
		"actiontype": "sign",
		"isexmaineable": 1,
		"groupType": "4",
		"code": "2000000007928",
		"idnumber": "",
		"dataStatus": 0,
		"ismustaudit": 1,
		"force_photo": 0,
		"isEnd": 0,
		"ismulti": 0,
		"isShow": 1,
		"auditorder": 2,
		"isinputidnumber": 0,
		"electronicSignature": [{
			"imgStr": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAjjSURBVHic7d1PqOZlFQfwc+c6ziIdiWkxY4Yw/sHAjREaKqELCWphght1k4VQCKYI\nLpQMChca2M5IEVpFJPkHbZUgiogKJiEOJFRCIqKmMqmTTnPHRSDq77wN49znPe/v3M8H3s2z+i4u\nly/nPM/7RgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADM0bURcfgTHwCATXf4M58Ha+MAAN3cEtPC8Upp\nIgCgnc+WjcMR8ePSRABAKzdGXjgAADZNVjYeLU0EALTylzDdAAAG2hV52bi7MhR80lp1AACO2aJJ\nhv/xrIxt1QEAOCY3Lzi/aJkhAIDeslXKv0sTAQCtvBl54bBKAQA2xXmRl407K0PBIlowwDy5KMqs\nuDQKMD/PLDjfvdQUAEBbX458lfJ0ZSg4EqM3gHmxSmGWrFQA5uM3C86/scwQAEBfx0e+SnmtMhQA\n0MvB8ONsAMBA10VeNm6qDAVHwyUjgNWXTTIOh3t4zIg/VoDV9vcF5zuXmgIAaGtv5KuU+ytDwedh\npQKwunznBm1YqQCspp8tOP/6UlMAAK1lq5S3SxMBAK38LfLCYZUCAGyKPZGXjXsqQ8Gx0pYBVouL\norTk0ijA6vjBgvMLl5oCAGgtW6W8V5oIAGjlkcgLx47KUABAH+uRl40nK0MBAL28FX56HgAY6PTI\ny8Z1laFgs3lmBVDLM1i2BM9iAepcs+D8jKWmAABay1Yp+0sTAQCt/DbywrG9MhQA0EtWNh4vTQQA\ntPJyeAYLAAy0M/KycWtlKACglw/DdAMAGOicyMvGeZWhAIBesrLxYWkiAKCV70VeOE4szAQANJOV\njX2liQCAVm4LF0UBgMGysvFwaSIAoJXfh+kGADBYVjbuLE0EALTyQphuAAADrUdeNn5YGQoA6OVf\nYboBAAz0hcjLxvmVoQCAXt4J0w0AYKCTIi8bZ1WGAgB6eTemZeNQaSIAoJVdkU839laGAgB6ORDT\nsvHf0kQAQCuLphtfqQwFAPRiugEADLU78unG7spQAEAvH8S0bHxQmggAaGVP5NONXZWhAIBe3o9p\n2ThQmggAaOWEyKcbX6oMBQD08nZMy8bB0kQAQCvHRz7dOLUyFADQy8sxLRsblYEAgF7WIp9ufK0y\nFADQy3ORFw4AgE2TlY3vlCYCAFr5Y5huAACDZWXj6tJEAEAr94bpBgAwWFY2bipNBAC0ckOYbgAA\ng2Vl49eliQCAVi4J0w0AYLCsbDxZmggAaOXkyAvHWmUoAKCX92NaNl4vTQQAtLLoJ+hPrAwFAPTy\n15iWjYOliQCAdrLpxtmliQCAVv4QnsICAINlZeOK0kQAQCu+xhwAGC4rG7eXJgIAWtkbphsAwGDv\nxbRs7CtNBAC0shb5dGNHZSgAoJc/xbRsHCpNBAC0k003Li5NBAC0cmO4LAoADJaVjTtKEwEArXw1\nTDcAgME8hQUAhtoWnsICAIPdH57CAgCDeQoLAAx1QbgsCgAM9p+Ylo0HShNBU2vVAQAKZdOM9YjY\nWHYQ6G5bdQCAIr9ccK5sAACbJru7cVVpIgCglT3hsigAMNirMS0bfy5NBAC0k003TipNBAC0cn1Y\npwAAg2Vl4+bSRABAK9vDdAMAGOx3MS0bb5QmAgDayaYb55YmAgBaOSGsUwCAwR6Nadl4oTQRANBO\nNt04pTQRANDKKWGdAgAM9nxMy8ZjpYkAgHay6cYXSxMBAK2cE9YpAMBg/4xp2bivNBEA0E423dhe\nmggAaOWbYZ0CAAz2j5iWjV+VJgIA2smmG+uliWCL2lYdAGCQnQvODy01BQDQ2n0xnW48UZoIAGgn\nW6ecVZoItrC16gAAg2SvUfzPgyLucAAd/SQ527/0FABAa9k65crSRLDFGS8CHVmnwIqxUgG6ubQ6\nAADQ35sxXaf8ojQRANCObxeFFWSlAnTi20UBgOHujul049nSRABAO9k65fzSREBEeCYG9OI5LKwo\ndziALr5VHQAA6G9feA4LAAyW3d/YUZoI+JjdJtDBWkRsLDgHVoA7HEAHP03OXll6CgCgtY2YrlMu\nL00EfIpxI9CB57Cw4qxUgLk7szoAANDfQzFdpzxQmggAaCd7DntaaSJgwo4TmDv3N2AG3OEA5uy7\nyVlWQAAAPreXYrpO+XlpIgCgnez+xnppIiBlzwnMmfsbMBPucABzdX1y9vrSUwAArb0b03XK90sT\nAQsZPQJzZZ0CM2KlAszRcdUBgKOjcABzdEty9uLSUwAArR2I6f2Ny0oTAf+XfScwR+5vwMxYqQAA\nwykcwNx8Oznbv/QUwFFROIC5yb5r466lpwAAWst+P+WM0kTAEblkBcyNC6MwQ1YqAMBwCgcwdxvV\nAYAjUziAubukOgAA0NNT8b+7HD+qDgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nbHUfAarA6sUrvYrrAAAAAElFTkSuQmCC\n",
			"uuid": ""
		}],
		"name": "确认人",
		"audittype": "sign,card",
		"specialworktype": "",
		"value": "iVBORw0KGgoAAAANSUhEUgAAAhwAAAGhCAYAAAAqQm1KAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAAAjjSURBVHic7d1PqOZlFQfwc+c6ziIdiWkxY4Yw/sHAjREaKqELCWphght1k4VQCKYI\nLpQMChca2M5IEVpFJPkHbZUgiogKJiEOJFRCIqKmMqmTTnPHRSDq77wN49znPe/v3M8H3s2z+i4u\nly/nPM/7RgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADM0bURcfgTHwCATXf4M58Ha+MAAN3cEtPC8Upp\nIgCgnc+WjcMR8ePSRABAKzdGXjgAADZNVjYeLU0EALTylzDdAAAG2hV52bi7MhR80lp1AACO2aJJ\nhv/xrIxt1QEAOCY3Lzi/aJkhAIDeslXKv0sTAQCtvBl54bBKAQA2xXmRl407K0PBIlowwDy5KMqs\nuDQKMD/PLDjfvdQUAEBbX458lfJ0ZSg4EqM3gHmxSmGWrFQA5uM3C86/scwQAEBfx0e+SnmtMhQA\n0MvB8ONsAMBA10VeNm6qDAVHwyUjgNWXTTIOh3t4zIg/VoDV9vcF5zuXmgIAaGtv5KuU+ytDwedh\npQKwunznBm1YqQCspp8tOP/6UlMAAK1lq5S3SxMBAK38LfLCYZUCAGyKPZGXjXsqQ8Gx0pYBVouL\norTk0ijA6vjBgvMLl5oCAGgtW6W8V5oIAGjlkcgLx47KUABAH+uRl40nK0MBAL28FX56HgAY6PTI\ny8Z1laFgs3lmBVDLM1i2BM9iAepcs+D8jKWmAABay1Yp+0sTAQCt/DbywrG9MhQA0EtWNh4vTQQA\ntPJyeAYLAAy0M/KycWtlKACglw/DdAMAGOicyMvGeZWhAIBesrLxYWkiAKCV70VeOE4szAQANJOV\njX2liQCAVm4LF0UBgMGysvFwaSIAoJXfh+kGADBYVjbuLE0EALTyQphuAAADrUdeNn5YGQoA6OVf\nYboBAAz0hcjLxvmVoQCAXt4J0w0AYKCTIi8bZ1WGAgB6eTemZeNQaSIAoJVdkU839laGAgB6ORDT\nsvHf0kQAQCuLphtfqQwFAPRiugEADLU78unG7spQAEAvH8S0bHxQmggAaGVP5NONXZWhAIBe3o9p\n2ThQmggAaOWEyKcbX6oMBQD08nZMy8bB0kQAQCvHRz7dOLUyFADQy8sxLRsblYEAgF7WIp9ufK0y\nFADQy3ORFw4AgE2TlY3vlCYCAFr5Y5huAACDZWXj6tJEAEAr94bpBgAwWFY2bipNBAC0ckOYbgAA\ng2Vl49eliQCAVi4J0w0AYLCsbDxZmggAaOXkyAvHWmUoAKCX92NaNl4vTQQAtLLoJ+hPrAwFAPTy\n15iWjYOliQCAdrLpxtmliQCAVv4QnsICAINlZeOK0kQAQCu+xhwAGC4rG7eXJgIAWtkbphsAwGDv\nxbRs7CtNBAC0shb5dGNHZSgAoJc/xbRsHCpNBAC0k003Li5NBAC0cmO4LAoADJaVjTtKEwEArXw1\nTDcAgME8hQUAhtoWnsICAIPdH57CAgCDeQoLAAx1QbgsCgAM9p+Ylo0HShNBU2vVAQAKZdOM9YjY\nWHYQ6G5bdQCAIr9ccK5sAACbJru7cVVpIgCglT3hsigAMNirMS0bfy5NBAC0k003TipNBAC0cn1Y\npwAAg2Vl4+bSRABAK9vDdAMAGOx3MS0bb5QmAgDayaYb55YmAgBaOSGsUwCAwR6Nadl4oTQRANBO\nNt04pTQRANDKKWGdAgAM9nxMy8ZjpYkAgHay6cYXSxMBAK2cE9YpAMBg/4xp2bivNBEA0E423dhe\nmggAaOWbYZ0CAAz2j5iWjV+VJgIA2smmG+uliWCL2lYdAGCQnQvODy01BQDQ2n0xnW48UZoIAGgn\nW6ecVZoItrC16gAAg2SvUfzPgyLucAAd/SQ527/0FABAa9k65crSRLDFGS8CHVmnwIqxUgG6ubQ6\nAADQ35sxXaf8ojQRANCObxeFFWSlAnTi20UBgOHujul049nSRABAO9k65fzSREBEeCYG9OI5LKwo\ndziALr5VHQAA6G9feA4LAAyW3d/YUZoI+JjdJtDBWkRsLDgHVoA7HEAHP03OXll6CgCgtY2YrlMu\nL00EfIpxI9CB57Cw4qxUgLk7szoAANDfQzFdpzxQmggAaCd7DntaaSJgwo4TmDv3N2AG3OEA5uy7\nyVlWQAAAPreXYrpO+XlpIgCgnez+xnppIiBlzwnMmfsbMBPucABzdX1y9vrSUwAArb0b03XK90sT\nAQsZPQJzZZ0CM2KlAszRcdUBgKOjcABzdEty9uLSUwAArR2I6f2Ny0oTAf+XfScwR+5vwMxYqQAA\nwykcwNx8Oznbv/QUwFFROIC5yb5r466lpwAAWst+P+WM0kTAEblkBcyNC6MwQ1YqAMBwCgcwdxvV\nAYAjUziAubukOgAA0NNT8b+7HD+qDgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nbHUfAarA6sUrvYrrAAAAAElFTkSuQmCC\n",
		"isbrushposition": 0,
		"disporder": 2
	}],
	"voList": [{
		"downlimit": 0,
		"groupType": "3",
		"code": "combustible",
		"isincludeboundary": 1,
		"name": "可燃气",
		"dataStatus": 0,
		"value": "0.1",
		"isShow": 1,
		"upperlimit": 0.5
	}, {
		"code": "detectiontype",
		"value": "retest"
	}, {
		"code": "gasdetectionid",
		"value": ""
	}, {
		"code": "analysisname",
		"value": "格尔木"
	}, {
		"code": "part",
		"value": ""
	}, {
		"code": "workticketid",
		"value": workticketidx
	}, {
		"code": "detectiontime",
		"value": now
	}, {
		"code": "iscomplete",
		"value": "0"
	}, {
		"code": "created_by",
		"value": ""
	}, {
		"code": "created_dt",
		"value": ""
	}, {
		"code": "updated_by",
		"value": 2000000012062
	}, {
		"code": "updated_dt",
		"value": ""
	}, {
		"code": "tenantid",
		"value": 2000000001003
	}, {
		"code": "remark",
		"value": "好咧"
	}]
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuitm35.append(caseinfo.copy())

#作业处理
workticketidx = workticketid + 3
caseinfo['id'] = 3408
caseinfo['name'] = '作业处理-用火作业-恢复-分析人签字'
#http://192.168.6.156/m/hse_m/HSE_WORKTASK_INJOB_M/recoverSaveAudit.json?workticketid=2000000003772&workType=dh&work
url = 'http://192.168.6.156/m/hse_m/HSE_WORKTASK_INJOB_M/recoverSaveAudit.json?workticketid=%d&workType=dh&work'%(workticketidx)
data = {
	"mainAttributeVO": {
		"cardnum": "16143013651646800519",
		"saveApprvoalInfo": "true",
		"person_type": "orgperson",
		"idnumber": "",
		"busdata": {
			"cardnum": "16143013651646800519",
			"person_type": "orgperson",
			"dataStatus": 0,
			"personid": 2000000016201,
			"person_name": "赵成"
		},
		"person_name": "赵成",
		"personid": 2000000016201,
		"specialworktype": "",
		"uuid": "1592962796571"
	},
	"auditPlainLineList": [{
		"actiontype": "card",
		"isexmaineable": 1,
		"groupType": "4",
		"code": "2000000007454",
		"personList": [{
			"cardnum": "16143013651646800519",
			"saveApprvoalInfo": "true",
			"person_type": "orgperson",
			"idnumber": "",
			"busdata": {
				"cardnum": "16143013651646800519",
				"person_type": "orgperson",
				"dataStatus": 0,
				"personid": 2000000016201,
				"person_name": "赵成"
			},
			"person_name": "赵成",
			"personid": 2000000016201,
			"specialworktype": "",
			"uuid": "1592962796571"
		}],
		"idnumber": "",
		"dataStatus": 0,
		"ismustaudit": 1,
		"force_photo": 1,
		"isEnd": 1,
		"ismulti": 0,
		"isShow": 1,
		"auditorder": 5,
		"isinputidnumber": 0,
		"name": "分析人",
		"audittype": "card",
		"specialworktype": "",
		"value": "",
		"isbrushposition": 1,
		"disporder": 5
	}],
	"voList": [{
		"downlimit": 0,
		"groupType": "3",
		"code": "combustible",
		"isincludeboundary": 1,
		"name": "可燃气",
		"dataStatus": 0,
		"value": "0.1",
		"isShow": 1,
		"upperlimit": 0.5
	}, {
		"code": "detectiontype",
		"value": "retest"
	}, {
		"code": "gasdetectionid",
		"value": 2000000001928
	}, {
		"code": "analysisname",
		"value": "格尔木"
	}, {
		"code": "part",
		"value": ""
	}, {
		"code": "workticketid",
		"value": 2000000003772
	}, {
		"code": "detectiontime",
		"value": now
	}, {
		"code": "iscomplete",
		"value": "0"
	}, {
		"code": "created_by",
		"value": ""
	}, {
		"code": "created_dt",
		"value": ""
	}, {
		"code": "updated_by",
		"value": 2000000012062
	}, {
		"code": "updated_dt",
		"value": ""
	}, {
		"code": "tenantid",
		"value": 2000000001003
	}, {
		"code": "remark",
		"value": "好咧"
	}]
}
caseinfo['url'] = url
caseinfo['data'] =data
testsuitm35.append(caseinfo.copy())


