{
	'status': 3200,
	'data': {
		'messages': None,
		'readonly': False,
		'btnList': [{
			'updated_dt': '2018-11-01 13:09:57',
			'btn_img': None,
			'btn_history': None,
			'formid': 2971435,
			'form_code': 'HSE_WORK_APPOINT_M',
			'df': 0,
			'btn_comment': None,
			'ver': 1,
			'btn_show_control': None,
			'btn_id': 2971725,
			'dataStatus': 0,
			'btn_order': 2,
			'btn_isenable': 1,
			'btn_name': '保存',
			'product_flag': 1,
			'btn_param': None,
			'btn_type': 'card_top',
			'tenantid': 1,
			'created_by': 1000,
			'btn_code': 'cardSave',
			'ts': None,
			'updated_by': 1000,
			'tableName': 'sy_form_button_mobile',
			'created_dt': '2018-11-01 13:09:57',
			'btn_inputconfig': None,
			'btn_group': 'modify',
			'btn_show_group': None
		}, {
			'updated_dt': '2019-11-25 15:13:32',
			'btn_img': None,
			'btn_history': 1,
			'formid': 2971435,
			'form_code': 'HSE_WORK_APPOINT_M',
			'df': 0,
			'btn_comment': None,
			'ver': 1,
			'btn_show_control': None,
			'btn_id': 1000000000000,
			'dataStatus': 0,
			'btn_order': 9,
			'btn_isenable': 1,
			'btn_name': '复制',
			'product_flag': 1,
			'btn_param': None,
			'btn_type': 'card_top',
			'tenantid': 1,
			'created_by': 1000,
			'btn_code': 'saveAndCopy',
			'ts': None,
			'updated_by': 1000,
			'tableName': 'sy_form_button_mobile',
			'created_dt': '2019-11-25 15:13:00',
			'btn_inputconfig': None,
			'btn_group': 'query',
			'btn_show_group': None
		}],
		'data': {
			'tenantid': 1,
			'updated_dt': '2020-06-10 14:17:20',
			'worktaskid_no': 0,
			'workunitname_no': None,
			'created_by': None,
			'df': 0,
			'ver': 1,
			'insert__': 'c6532c292a49456f9858363d1d0b08dc',
			'ts': None,
			'updated_by': None,
			'dataStatus': 0,
			'tableName': 'hse_work_appoint',
			'created_dt': '2020-06-10 14:17:20',
			'status': 'draft',
			'isreport': '1'
		}
	}
}